### ISSUE TITLE
Can't install it properly on localhost

### ISSUE THREAD

**Issue by tqk-gh** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#104]
So i'm using apache httpd service for localhost, my localhost dir in /etc/httpd/conf/httpd.conf is /srv/http/shop
I put all the website files in that dir as well, I had to replace the __autoload() with spl_autoload_register() at first cause it wouldn't load. 
Now it's not showing errors, but it's loading a very basic html file ![like this](https://user-images.githubusercontent.com/29256024/45500165-9b27bd00-b7b0-11e8-9b7f-d00f409ccb1f.png)
No css or proper directing to pages (I get **error 404** when trying to go to **Contacts** page for example)

Removing the "RewriteBase /" line from **.htaccess** and changing the **Allowoverdrive** in /etc/httpd/conf/httpd.conf option from **None** to **All**, results in a **Error 500**
![error 500](https://user-images.githubusercontent.com/29256024/45500313-f194fb80-b7b0-11e8-91e5-b0dd1b4abee4.png)

It's my second time dealing with Codeigniter, so excuse me if I'm missing something basic.

**Comment by kirilkirkov** [comment]
@tqk-gh Are you set base_url in application/config/config.php with yours? Try to add virtual host and add it to base_url, example: "shop.localhost"  in /etc/apache2/sites-available and set it to open /srv/http/shop. Then in base_url variable set "http://shop.localhost" and you will have css ;)

**Comment by tqk-gh** [comment]
Thanks for the reply, but I tried it and it's still not working.
This is the output of the command `# /usr/bin/httpd -S`

> VirtualHost configuration:
*:80                   shop.localhost.com (/etc/httpd/conf/extra/httpd-vhosts.conf:24)
ServerRoot: "/etc/httpd"
Main DocumentRoot: "/srv/http/shop"
Main ErrorLog: "/var/log/httpd/error_log"
Mutex default: dir="/run/httpd/" mechanism=default 
Mutex mpm-accept: using_defaults
PidFile: "/run/httpd/httpd.pid"
Define: DUMP_VHOSTS
Define: DUMP_RUN_CFG
User: name="http" id=33 not_used
Group: name="http" id=33 not_used

I have added `127.0.1.1        shop.localhost.com` in my `/etc/hosts` and I set `shop/application/config/config.php` to *config['base_url'] = 'http://shop.localhost.com';*
Still no proper styling, and none of the other pages is accessible.
![Picture](https://user-images.githubusercontent.com/29256024/45591066-f8bb3580-b979-11e8-81d1-1c9d906e1667.png)

**Comment by kirilkirkov** [comment]
@tqk-gh Are you sure that your .htaccess file working?
If you use apache -
1. a2enmod rewrite
2. AllowOverride All  - to virtual host
3. Restart apache

Also give 777 permissions to all directories.  There is no problem in platform. Someting in your server is the problem

**Comment by tqk-gh** [comment]
Yeah, it's definitely an issue with my server. 

I used `$ sudo a2enmod rewrite` and uncommented the line `LoadModule rewrite_module modules/mod_rewrite.s` in `/etc/httpd/conf/httpd.conf` so now it everything is working fine.

Thanks a lot for the help!! (y)
