### ISSUE TITLE
error reported importing database.sql 

### ISSUE THREAD

**Issue by hahadaba** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#105]
CREATE TABLE  `vendors` (

 `id` INT( 11 ) NOT NULL ,
 `name` VARCHAR( 50 ) DEFAULT NULL ,
 `url` VARCHAR( 50 ) NOT NULL ,
 `email` VARCHAR( 50 ) NOT NULL ,
 `password` VARCHAR( 100 ) NOT NULL ,
 `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
 `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE = INNODB DEFAULT CHARSET = utf8;

MySQL 返回: 文档

#1293 - Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause

**Comment by ruey-agcang** [comment]
Bro, did your website load successfully? Please reply

**Comment by kirilkirkov** [comment]
@hahadaba 
Ok make it like this:


CREATE TABLE `vendors` (
  `id` int(11) NOT NULL,
  `name` varchar(50) DEFAULT NULL,
  `url` varchar(50) NOT NULL,
  `email` varchar(50) NOT NULL,
  `password` varchar(100) NOT NULL,
  `updated_at` timestamp NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

It is no problem!
