### ISSUE TITLE
How to add products via phpmyadmin manually/ How to access admin/vendor pages

### ISSUE THREAD

**Issue by ruey-agcang** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#106]
How can I add products/blogs/categories 
![capture](https://user-images.githubusercontent.com/43297079/45587292-8412d780-b936-11e8-8e85-8619441dbcdf.JPG)
manually through phpmyadmin? And also, how can I access the admin/vendor page? Is there other ways to integrate other templates included in your project? I'm a newbie by the way. THANK YOU SO MUCH

**Comment by kirilkirkov** [comment]
@ruey-agcang 
All you can add from /admin with username and password "admin". Admin vendor page must be enabled from /admin -> settings , and you will see login/register fileds at the top of your template.
