### ISSUE TITLE
public user login page not working

### ISSUE THREAD

**Issue by yanhuangpai** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#107]
What am I trying to do..
..What's happening 
Hi, thank you so much for your project. But seems that public user login page not working, as there is no login.php file in the template.

**Comment by kirilkirkov** [comment]
@yanhuangpai login.php? When you are redirected to this file? 
I test it now and it is working. You say "vendor login" page?

![screenshot_2018-09-17 user login](https://user-images.githubusercontent.com/3421328/45628632-264ccf80-ba9d-11e8-9bb6-22e907eabd48.png)

**Comment by kirilkirkov** [comment]
@yanhuangpai Only "greenlabel" template have MultiVendor
