### ISSUE TITLE
Template Use

### ISSUE THREAD

**Issue by akash80** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#108]
these scripts and css files aren't working. Could you please help me to set up the project.

<link href="http://localhost/ecommerce/templatecss/custom.css" rel="stylesheet" />
  | <link href="http://localhost/ecommerce/cssloader/theme.css" rel="stylesheet" />
  | <script src="http://localhost/ecommerce/loadlanguage/all.js"></script>

**Comment by kirilkirkov** [comment]
@akash80 This file location is in "application/language/bulgarian/js/". Maybe you have problem with your server configuration, i check and file is loaded successful
