### ISSUE TITLE
Pls Help: Product Grid View has products not properly displayed

### ISSUE THREAD

**Issue by studuino** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#109]
![image](https://user-images.githubusercontent.com/2291009/46605467-9fc96200-cb1f-11e8-8475-57de5acfaafd.png)

**Comment by kirilkirkov** [comment]
@studuino Can you give me the website link in production to check it?

**Comment by kirilkirkov** [comment]
@studuino I think this is old version of this platform. Give me link in production and will give you css fix

**Comment by studuino** [comment]
@kirilkirkov Thank you for your reply. this is not a production site yet. I am setting up in my windows PC localhost environment.

**Comment by studuino** [comment]
@kirilkirkov I tried upload the website at https://tinyurl.com/ybeqgpcj . 
I think CSS need be adjusted or fixed. menu Links do not go to where as expected (like in localhost).

**Comment by kirilkirkov** [comment]
@studuino update your platform with last version on github or add this css - 

.product-list .inner .img-container a img { height : 200px; }

**Comment by kirilkirkov** [comment]
the reason for this problem is that there is no added photo height and this brokes design.
