### ISSUE TITLE
help wanted: Social Media Links do not redirect to destined address

### ISSUE THREAD

**Issue by studuino** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#110]
In Admin Panel, I configured as below
![image](https://user-images.githubusercontent.com/2291009/46667682-5a289a00-cbf0-11e8-85d0-774386c8e93b.png)

In production site, it goes to 
https://mydomain.com/www.facebook.com/destination23

How should I make it right?
Thanks.

**Comment by kirilkirkov** [comment]
@studuino add https:// before www.facebook

**Comment by studuino** [comment]
@kirilkirkov Thank you for your prompt support. Most appreciated.

**Comment by kirilkirkov** [comment]
@studuino 
If this project help you reduce time to develop, you can give me a cup of coffee to continue its development. Thank you! :)
https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=W5BR6K29BQX7E
