### ISSUE TITLE
I am getting an issue with this error

### ISSUE THREAD

**Issue by senjoy11** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#115]
Hello Sir,
I am getting an issue with this error
A PHP Error was encountered
Severity: 8192

Message: __autoload() is deprecated, use spl_autoload_register() instead

Filename: PHPMailer/PHPMailerAutoload.php

Line Number: 45

Backtrace:

File: E:\XAMP\htdocs\Shop\application\libraries\SendMail.php
Line: 4
Function: _error_handler

File: E:\XAMP\htdocs\Shop\application\libraries\SendMail.php
Line: 4
Function: require

File: E:\XAMP\htdocs\Shop\application\third_party\MX\Loader.php
Line: 173
Function: _ci_load_library

File: E:\XAMP\htdocs\Shop\application\third_party\MX\Loader.php
Line: 190
Function: library

File: E:\XAMP\htdocs\Shop\application\third_party\MX\Loader.php
Line: 153
Function: libraries

File: E:\XAMP\htdocs\Shop\application\third_party\MX\Loader.php
Line: 65
Function: initialize

File: E:\XAMP\htdocs\Shop\application\third_party\MX\Base.php
Line: 55
Function: __construct

File: E:\XAMP\htdocs\Shop\application\third_party\MX\Base.php
Line: 60
Function: __construct

File: E:\XAMP\htdocs\Shop\application\third_party\MX\Controller.php
Line: 4
Function: require

File: E:\XAMP\htdocs\Shop\application\third_party\MX\Modules.php
Line: 123
Function: include_once

File: E:\XAMP\htdocs\Shop\application\core\MY_Controller.php
Line: 3
Function: spl_autoload_call

File: E:\XAMP\htdocs\Shop\index.php
Line: 292
Function: require_once

**Comment by kirilkirkov** [comment]
@senjoy11 
https://github.com/kirilkirkov/Ecommerce-CodeIgniter-Bootstrap/issues/86

**Comment by kirilkirkov** [comment]
@senjoy11 
Or just get this fix :)  - https://github.com/kirilkirkov/Ecommerce-CodeIgniter-Bootstrap/commit/14193ee12d225720c040ac681e50c97e9b924da8
