### ISSUE TITLE
Help me solve this

### ISSUE THREAD

**Issue by philipsfuture** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#117]
Warning: require_once(C:/xampp/htdocs/Ecommerce/system/core/Common.php): failed to open stream: No such file or directory in C:\xampp\htdocs\Ecommerce\system\core\CodeIgniter.php on line 80

Fatal error: require_once(): Failed opening required 'C:/xampp/htdocs/Ecommerce/system/core/Common.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\Ecommerce\system\core\CodeIgniter.php on line 80

**Comment by kirilkirkov** [comment]
@philipsfuture it seems you have missing files? Try to download again the application and install it
