### ISSUE TITLE
Add brand at vendor

### ISSUE THREAD

**Issue by muhammadfakhriaf** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#118]
Hi, Kiril Kirkov
Can you add brand at vendor ?

Thank you for your all

**Comment by kirilkirkov** [comment]
@muhammadfakhriaf 
Added -  https://github.com/kirilkirkov/Ecommerce-CodeIgniter-Bootstrap/commit/8fe79e58795682134a687a51f451e3b9f788dd8f
