### ISSUE TITLE
Question about additional feature

### ISSUE THREAD

**Issue by mnestorov** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#119]
Hi Kiril, and BIG thank you for your amazing work!

I want to ask you, Is there a feature like this one: Users will add and sell their product/products. Admin will earn money from every sale. For example, 10 percentage of every sale. Something like "subscription packages for vendors", which packages can be managed from admins?

Regards,
Martin

**Comment by kirilkirkov** [comment]
@mnestorov Hi Martin. Yes, vendors can add and sell their products. All published products from vendors are visible in public page and also in administration and the admin can manage them. Every sell on the site is visible in admin/orders and there you can see if the order is from vendors product or not. When you complete orders you can give the percent to vendors.

**Comment by zhenguanyimin** [comment]
@kirilkirkov  

> 

"When you complete orders you can give the percent to vendors" how to do that?

**Comment by kirilkirkov** [comment]
@zhenguanyimin 
this very much depends on the functionality that the creators of the site want, so you can change the functionality as you want if have coding skills. Currently i am working on implementation of the section with list of all vendors and their sales. I will thing about some general solutions to track their orders
