### ISSUE TITLE
help wanted: Facebook Messenger Chat Plugin

### ISSUE THREAD

**Issue by studuino** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#121]
Hi @kirilkirkov 
I am trying to add facebook customer chat features
I am a bit confused using FB's js link whether it should be in administrator's settings [Add google or other JavaScript to site] or hardcode in the home.php. 

the facebook messenger chat plugin is as follows:
![image](https://user-images.githubusercontent.com/2291009/48822182-75a7c880-ed8a-11e8-9a31-36ce018223fc.png)

Tried both ways, still cant make it works(message pop-up doesn't show up).

**Comment by kirilkirkov** [comment]
@studuino  If you add messagner plugin in enabled template home.php must work. Check console log of browser for errors. Maybe the problem is in your plugin code.
