### ISSUE TITLE
css,js and url issue

### ISSUE THREAD

**Issue by manigopal** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#125]
just followed your steps css & js are not loading even the url / files are present -- checked using view page source & also the links go to localhost/dashboard.

**Comment by kirilkirkov** [comment]
@manigopal do you have .htaccess file and it is used from apache?

**Comment by gopalgoandroy** [comment]
yes i do use... apache

I'm using xampp server at localhost.

**Comment by manigopal** [comment]
yes i do use the apache

xampp local server @kirilkirkov

**Comment by kirilkirkov** [comment]
@manigopal  and .htaccess is loaded from apache ?

**Comment by manigopal** [comment]
i dont get you ? i dont understand

**Comment by kirilkirkov** [comment]
@manigopal the problem maybe is in your .htaccess. 
Check you apache configuration. Must be (example):
<Directory "/www/htdocs">
    AllowOverride All
</Directory>

**Comment by manigopal** [comment]
where do i find this ? 

since i havent modified your .htaccess which already present.

**Comment by kirilkirkov** [comment]
@manigopal yes, it present but apache dont use it (maybe).
https://stackoverflow.com/questions/17162214/htaccess-not-working-on-localhost-with-xampp

Check in google please.
