### ISSUE TITLE
how to multi-vendor create?

### ISSUE THREAD

**Issue by avinashwatwad** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#128]
What am I trying to new vendor create but i am not understand how to create please explain me.

**Comment by kirilkirkov** [comment]
@avinashwatwad 
Login url is - vendor/login. Vendors are not supported only from "onepage" template. Can register new vendor from url - vendor/register. Vendors must be enabled from /admin (administration) ->Settings->Multi-Vendor Support before try to use it.
