### ISSUE TITLE
Getting errors with php 7.3 (updated title)

### ISSUE THREAD

**Issue by AckeemPratt** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#129]
![screencapture-localhost-shop-2018-12-26-14_24_25](https://user-images.githubusercontent.com/45286873/50455128-19e8d600-091a-11e9-9627-142c9629908a.png)

A PHP Error was encountered
Severity: 8192

Message: strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior

Filename: MX/Router.php

Line Number: 239

Backtrace:

File: C:\xampp\htdocs\shop\application\third_party\MX\Router.php
Line: 239
Function: strpos

File: C:\xampp\htdocs\shop\application\third_party\MX\Router.php
Line: 101
Function: _set_default_controller

File: C:\xampp\htdocs\shop\index.php
Line: 292
Function: require_once

**Comment by kirilkirkov** [comment]
@AckeemPratt Which version of php use? This problem comming from the framework. You can update codeigniter with the last version, maybe this is fixed there

**Comment by kirilkirkov** [comment]
@AckeemPratt If you are using php 7.3 , this problem comes from HMVC module. I recommend you to use version 7.1 or lower or if you want to continue use it try with this fix in the MX\Router.php

```
public function set_class($class)
{
    $suffix = $this->config->item('controller_suffix');
    
        if( $suffix && strpos($class, $suffix) === FALSE)
    {
        $class .= $suffix;
    }

    parent::set_class($class);
} 
```

**Comment by AckeemPratt** [comment]
Tried the code above did not work for php 7.3. However decided i would just downgrade the php version to 7.1 now it work Thanks.

BTW is this a bug in the php it self or could something else be done for this to work on 7.3

**Comment by kirilkirkov** [comment]
@AckeemPratt  in the last post i paste code that can be changed in Router.php and the framework will work on php 7.3

**Comment by AckeemPratt** [comment]
Thank you.
