### ISSUE TITLE
After placing order, final amount is not storing in any database

### ISSUE THREAD

**Issue by gopal1996** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#132]
Hi
Thank you for your project.
After placing an order, the final amount is not storing into database not sending the details through email.
Even in admin page, final amount is not showing.
Can you please help to add the final amount in admin page.

**Comment by kirilkirkov** [comment]
@gopal1996  Thanks!
You can check this commit -  https://github.com/kirilkirkov/Ecommerce-CodeIgniter-Bootstrap/commit/a89fb067d6d6fd0453e465fa1a0c2da4bc332a74
Pull the last version and will have the new functionality

**Comment by gopal1996** [comment]
Thank you for your response. 
According to me if the product price is updated then it will be reflected in the previous orders also.
I guess there must be some logic to add price to the database after cart ie in payment success / order_success page.

**Comment by kirilkirkov** [comment]
@gopal1996 hmm , maybe the price should not change in old orders because they are already paid (for example)
I will fix it

**Comment by kirilkirkov** [comment]
@gopal1996  Try this - https://github.com/kirilkirkov/Ecommerce-CodeIgniter-Bootstrap/commit/b82cf93b89043238d62e0699bd6164a0dce7f55b

**Comment by kirilkirkov** [comment]
@gopal1996 i wait for your answer

**Comment by gopal1996** [comment]
@kirilkirkov Thank you for your response. We haven't tried that solution yet, we will try and respond you back in end of the day.

**Comment by gopal1996** [comment]
@kirilkirkov Thank you for your time and response.. That code is working like charm.
