### ISSUE TITLE
Sometimes Adding to shopping cart is not working

### ISSUE THREAD

**Issue by gopal1996** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#133]
Sometimes when I click adding to shopping cart or buy now in the home page product list, it showing error "**Problem with shopping cart! Try again!**". 
no 'access-control-allow-origin' header is present on the requested resource

Thank you :)

**Comment by Gokul2104** [comment]
This could be your url switching between **www** and **non-www** or **http** and **https** this could happen only when home page is loaded directly and to solve this make it constant ie what domain you have defined in the config file and use **htaccess** to redirect to it.

**Comment by gopal1996** [comment]
Thank you @Gokul2104 . I redirect non www to www in htaccess file. now its working as expected.
@kirilkirkov Thank you
