### ISSUE TITLE
Error loading sessions

### ISSUE THREAD

**Issue by ojpeters** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#134]
Hello, It appears there is an issue with the way HMVC loads sessions, I am getting the following message.Can you help?
Filename: Session/Session.php

Line Number: 143

Backtrace:

File: /home/ischolar/public_html/shop/application/third_party/MX/Loader.php
Line: 173
Function: _ci_load_library

File: /home/ischolar/public_html/shop/application/third_party/MX/Loader.php
Line: 190
Function: library

File: /home/ischolar/public_html/shop/application/third_party/MX/Loader.php

**Comment by kirilkirkov** [comment]
@ojpeters I am not familiar with this errors. Try to update HMVC - https://bitbucket.org/wiredesignz/codeigniter-modular-extensions-hmvc/downloads/
