### ISSUE TITLE
Display brand name in product view page

### ISSUE THREAD

**Issue by gopal1996** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#135]
Hi,
Is it possible to display brand name in the single product view page.
This will help to identify this products is belongs to this brand.
Just request.. 
If possible please help.

**Comment by kirilkirkov** [comment]
@gopal1996 Yes it is. in a getOneProduct method on Public_model add join with brands table with brands.id = products.brand_id and get in the select brands.name as brand_name :)

**Comment by gopal1996** [comment]
Thank you
