### ISSUE TITLE
I want to use this shop system as a multi-site system

### ISSUE THREAD

**Issue by saeedisfahani** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#136]
Hi dear friend.
First of all I appreciate for your good job.

My question is how can I use this system as a multi-site system?

My example address is shop.com

I want to have multiple subfolders as multiple shops. the subfolders are shopfolders actually.
I want to have one core system/code and use it for any shop subfolder.

like this:

main domain: http://shop.com
shopping1: http://shop.com/shopping1
shopping2: http://shop.com/shopping2

could you help me to solving this problem?

**Comment by kirilkirkov** [comment]
@saeedisfahani you have to search on google is there option for codeigniter to work with one system and multiple applications. 
This platform doesn't support multiple domains
