### ISSUE TITLE
cannot upload product image

### ISSUE THREAD

**Issue by figarjanuar** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#138]
i got error like this

> Access to XMLHttpRequest at 'javascript:void(0);' from origin 'http://localhost' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.

i have try to use cros origin extention from chrome, but nothing happen

**Comment by kirilkirkov** [comment]
@figarjanuar I can not reproduce it to me.
Upload on a real server, maybe error comes from your hosting. If on a real server have the same error send me url and i will check and recover

**Comment by figarjanuar** [comment]
i tried on my linux mint there was no problem with upload, but on my xampp windows it cannot upload

**Comment by kirilkirkov** [comment]
@figarjanuar Maybe the problem is in xampp configuration. I do not use Windows and i cant test.
