### ISSUE TITLE
change money

### ISSUE THREAD

**Issue by rainnervl** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#139]
How do I change the currency type?

**Comment by Kelows** [comment]
go to 
![image](https://user-images.githubusercontent.com/25620341/52591206-a6584500-2e43-11e9-9e0b-993e83ba64ed.png)

then
![image](https://user-images.githubusercontent.com/25620341/52591220-b112da00-2e43-11e9-9b66-9757f3af7e00.png)

in the admin page, in the language part, add a new language, make sure the currenyKey is the same that the $config['currencyKey']
![image](https://user-images.githubusercontent.com/25620341/52591313-eb7c7700-2e43-11e9-823e-2a5adf2a44d1.png)

**Comment by rainnervl** [comment]
thankyou!!!!
