### ISSUE TITLE
what type of file to add languages

### ISSUE THREAD

**Issue by rainnervl** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#140]
What am I trying to do..
..What's happening 
what type of file to add languages

**Comment by Kelows** [comment]
Is this a dream...

urwebsite.local/admin then connect with admin/admin

then on the left go to 
![image](https://user-images.githubusercontent.com/25620341/52591022-1914f080-2e43-11e9-9ab9-e59104476647.png)
 then click
![image](https://user-images.githubusercontent.com/25620341/52591042-24681c00-2e43-11e9-804a-bb85722ba940.png)

files are located here
![image](https://user-images.githubusercontent.com/25620341/52591059-38ac1900-2e43-11e9-9bb6-2f91ef02e395.png)

on the conf.php to set it default

**Comment by rainnervl** [comment]
thankyou, yes perfect but where I find spanish

**Comment by Kelows** [comment]
type it with your keyboard, this isn't automatic magic

**Comment by rainnervl** [comment]
Thankyou :)

**Comment by Kelows** [comment]
don't give up man

**Comment by rainnervl** [comment]
achieved, thanks!
