### ISSUE TITLE
Dynamic field for products in the cart

### ISSUE THREAD

**Issue by Kelows** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#141]
Hello,

I wonder where is the file that stores the order in the db when i click on make order in the checkout?

my goal is to have a dynamic field (boolean, that i can set when i add a new product to cart) for each product in my cart that i will see in the backoffice in the order details
if you could help me please....thanks:)

**Comment by kirilkirkov** [comment]
@Kelows In "application/models/Public_model.php" - method setOrder saves the order from checkout page to orders table in administration. Just add new filed there and create new column in orders table.
is this what you want?

**Comment by aswinsasi** [comment]
Sir can u add a ajax sorting products technology in website

**Comment by Kelows** [comment]
Yes thanks i'll try, i can add directly in the product field or i create a new one like "data" ?

**Comment by aswinsasi** [comment]
Thank you.sir
..if u updated sent me a confirm msg....sorting list is most wanted in
ecommerce like color size prize

**Comment by aswinsasi** [comment]
Sir also do me a online milk daily delivery website ...add monthly and
weekly, daily subscription on it..can u do for me...also that sorting
property add on ecommercs site of u its give more user friendly

**Comment by Kelows** [comment]
@aswinsasi please open a new case, its not the subjet of this one :)

**Comment by aswinsasi** [comment]
Sir i need a filter option for price, color and all...eg: when a shirt
order the size x,xl,xxl like filter option that i need...when click on a
product

**Comment by aswinsasi** [comment]
Sir how to add filter product option in project

**Comment by kirilkirkov** [comment]
@aswinsasi  You must create new column in products table with shirt size and add it to view of your template.

@Kelows When you have new order all information go to orders table. Your column must be there maybe

**Comment by aswinsasi** [comment]
sir,
how to get notification email when someone purchase a prdouct..and how to
make an invoice generator

**Comment by kirilkirkov** [comment]
@aswinsasi  Notification are explained in another issue from you.
Invoices are not supported

**Comment by aswinsasi** [comment]
please help sir,
sir,
when i click moreinfo button in admin/order .In order table when i click
moreinfo option the product details shown like below with error..what to
do??redlabel template i use..

Email [aswinfear01@gmail.com](mailto:aswinfear01@gmail.com)
City ggf
Address VALADITHEKKATHIL ,POTHAPPALLY SOUTH ,KUMARAPURAM P.O,
HARIPAD,ALAPPUZHA,690548
Postcode 690548
Notes
Come from site Direct traffic or referrer is not visible
Payment Type cashOnDelivery
Discount -%
Products
A PHP Error was encountered
Severity: Warning

Message: A non-numeric value encountered

Filename: ecommerce/orders.php

Line Number: 146

Backtrace:

File:
C:\xampp\htdocs\shop\application\modules\admin\views\ecommerce\orders.php
Line: 146
Function: _error_handler

File: C:\xampp\htdocs\shop\application\third_party\MX\Loader.php
Line: 355
Function: include

File: C:\xampp\htdocs\shop\application\third_party\MX\Loader.php
Line: 294
Function: _ci_load

File:
C:\xampp\htdocs\shop\application\modules\admin\controllers\ecommerce\Orders.php
Line: 73
Function: view

File: C:\xampp\htdocs\shop\index.php
Line: 292
Function: require_once

Product http://localhost/shop/
Quantity:
A PHP Error was encountered
Severity: Notice

Message: Array to string conversion

Filename: ecommerce/orders.php

Line Number: 156

Backtrace:

File:
C:\xampp\htdocs\shop\application\modules\admin\views\ecommerce\orders.php
Line: 156
Function: _error_handler

File: C:\xampp\htdocs\shop\application\third_party\MX\Loader.php
Line: 355
Function: include

File: C:\xampp\htdocs\shop\application\third_party\MX\Loader.php
Line: 294
Function: _ci_load

File:
C:\xampp\htdocs\shop\application\modules\admin\controllers\ecommerce\Orders.php
Line: 73
Function: view

File: C:\xampp\htdocs\shop\index.php
Line: 292
Function: require_once

Array / Price: ₹
Vendor:
Total amount of products: 0 ₹
