### ISSUE TITLE
login admin panel

### ISSUE THREAD

**Issue by deriswan** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#142]
when entering the admin panel and typing in the menu, always ask to log in again which part should I fix?

**Comment by kirilkirkov** [comment]
@deriswan Maybe you have error with sessions in your browser. Try with another browser. I will wait for your answer

**Comment by deriswan** [comment]
I downloaded the product and I tried to install it on direct hosting but still when the login is logged it can't be clicked and keeps asking for login. Please instructions to be able to fix it, thank you

**Comment by kirilkirkov** [comment]
@deriswan GIve me a link. If you try with another browser are you still have this problem?

**Comment by PopperDre** [comment]
kirilkirkov hie , +263 73 427 2264 can you app there
