### ISSUE TITLE
e-mail or sms notification

### ISSUE THREAD

**Issue by aswinsasi** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#143]
sir,
how we know when someone order for a product..can you give a notification option wehn someone book a product..

**Comment by kirilkirkov** [comment]
@aswinsasi You allready have. In application/controllers/Checkout.php find method sendNotifications() and there you can find the logic of notifications. The query is "SELECT email FROM users WHERE notify = 1". You admin account must have notify value 1 and you must have configured email server in  - application/libraries/SendMail.php

**Comment by aswinsasi** [comment]
thank you sir but now an eroor occuered sir in admin/orders new orderid not
confirmed msg shown what is that sir

**Comment by aswinsasi** [comment]
thank you sir but now an eroor occuered sir in admin/orders new orderid not
confirmed msg shown what is that sir  and when i click processed button
error with status change check log msg appear as popup

**Comment by aswinsasi** [comment]
A PHP Error was encountered

Severity: Warning

Message: A non-numeric value encountered

Filename: ecommerce/orders.php

Line Number: 146

Backtrace:

when i click admin/orders moreifo under product details this will appear

**Comment by kirilkirkov** [comment]
@aswinsasi I cant reproduce. Give me step by step

**Comment by aswinsasi** [comment]
Sir i cant get email notifiaction after i put my email address and password
on phpmailer ..
There is no notification ...what i need to change....the username and
password in sendmail() is changed witg my gmail email and password...what
to do to get notificaion

**Comment by aswinsasi** [comment]
Thank you.i got it
