### ISSUE TITLE
won't load

### ISSUE THREAD

**Issue by skouii** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#144]
hello,
so i downloaded this and followed instructions now i get this?
is there a fix?

![2019-02-19 22_11_07-404 page not found](https://user-images.githubusercontent.com/8681310/53047948-ddf26d00-3493-11e9-8005-9cc644438704.png)

**Comment by Kelows** [comment]
change the function name in the autoload file at line 45 to spl_autoload_register

**Comment by kirilkirkov** [comment]
@skouii fixed - https://github.com/kirilkirkov/Ecommerce-CodeIgniter-Bootstrap/commit/11d89fd0ccac266ea725b66d6eaa61dd9e0bd921
