### ISSUE TITLE
A PHP Error was encountered

### ISSUE THREAD

**Issue by aswinsasi** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#146]
admin/orders  and in order table when i click more info following error is occuered 

Products
--
A PHP Error was encountered
Severity: Warning
Message: A non-numeric value encounteredFilename: ecommerce/orders.php
Line Number: 146
Backtrace
:File: C:\xampp\htdocs\shop\application\modules\admin\views\ecommerce\orders.php
Line: 146
Function: _error_handler
File: C:\xampp\htdocs\shop\application\third_party\MX\Loader.php
Line: 355
Function: include
File: C:\xampp\htdocs\shop\application\third_party\MX\Loader.php
Line: 294
Function: _ci_load
File: C:\xampp\htdocs\shop\application\modules\admin\controllers\ecommerce\Orders.php
Line: 73
Function: view
File: C:\xampp\htdocs\shop\index.php
Line: 292
Function: require_once
http://localhost/shop/
Quantity:
A PHP Error was encountered
Severity: Notice
Message: Array to string conversion
Filename: ecommerce/orders.php
Line Number: 156Backtrace
:File: C:\xampp\htdocs\shop\application\modules\admin\views\ecommerce\orders.php
Line: 156
Function: _error_handler
File: C:\xampp\htdocs\shop\application\third_party\MX\Loader.php
Line: 355
Function: include
File: C:\xampp\htdocs\shop\application\third_party\MX\Loader.php
Line: 294Function: _ci_loadFile: C:\xampp\htdocs\shop\application\modules\admin\controllers\ecommerce\Orders.php
Line: 73
Function: view
File: C:\xampp\htdocs\shop\index.php
Line: 292
Function: require_once
Array / Price: ₹
Vendor:Total amount of products: 0 ₹

in product details how to avoid this error and get product details

**Comment by kirilkirkov** [comment]
@aswinsasi do you still have this problem?
