### ISSUE TITLE
A PHP Error was encountered

### ISSUE THREAD

**Issue by lampatt** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#148]
l followed your installation direction but when l run in the browser, the following is what displays and below is the homepage though it doesn't display correctly. Can you please help.
Severity: 8192

Message: __autoload() is deprecated, use spl_autoload_register() instead

Filename: PHPMailer/PHPMailerAutoload.php

Line Number: 46

Backtrace:

File: C:\xampp\htdocs\ecommerce_kiril\application\libraries\SendMail.php
Line: 4
Function: _error_handler

File: C:\xampp\htdocs\ecommerce_kiril\application\libraries\SendMail.php
Line: 4
Function: require

File: C:\xampp\htdocs\ecommerce_kiril\application\third_party\MX\Loader.php
Line: 173
Function: _ci_load_library

File: C:\xampp\htdocs\ecommerce_kiril\application\third_party\MX\Loader.php
Line: 190
Function: library

File: C:\xampp\htdocs\ecommerce_kiril\application\third_party\MX\Loader.php
Line: 153
Function: libraries

File: C:\xampp\htdocs\ecommerce_kiril\application\third_party\MX\Loader.php
Line: 65
Function: initialize

File: C:\xampp\htdocs\ecommerce_kiril\application\third_party\MX\Base.php
Line: 55
Function: __construct

File: C:\xampp\htdocs\ecommerce_kiril\application\third_party\MX\Base.php
Line: 60
Function: __construct

File: C:\xampp\htdocs\ecommerce_kiril\application\third_party\MX\Controller.php
Line: 4
Function: require

File: C:\xampp\htdocs\ecommerce_kiril\application\third_party\MX\Modules.php
Line: 123
Function: include_once

File: C:\xampp\htdocs\ecommerce_kiril\application\core\MY_Controller.php
Line: 3
Function: spl_autoload_call

File: C:\xampp\htdocs\ecommerce_kiril\index.php
Line: 292
Function: require_once

**Comment by lampatt** [comment]
l have got it resolved.
Note: If encountering problem when display in browser with php error, do the following;

1. remove from .htaccess file
"RewriteBase /"
2. if getting php error do the following:
open application/libraries/PHPMailer/PHPMailerAutoload.php
and change at line 46  __autoload to spl_autoload_register and it will work better

This is because autoload is deprecated. Hope that works for you.

**Comment by kirilkirkov** [comment]
@lampatt i know about this issue. Resolved - https://github.com/kirilkirkov/Ecommerce-CodeIgniter-Bootstrap/commit/11d89fd0ccac266ea725b66d6eaa61dd9e0bd921
