### ISSUE TITLE
product details with extra information

### ISSUE THREAD

**Issue by aswinsasi** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#151]
array(21) { ["vendor_url"]=> NULL ["id"]=> string(1) "1" ["folder"]=> string(10) "1550216421" ["image"]=> string(6) "a1.jpg" ["time"]=> string(10) "1550216686" ["time_update"]=> string(10) "1550216807" ["visibility"]=> string(1) "1" ["shop_categorie"]=> string(2) "37" ["quantity"]=> string(1) "2" ["procurement"]=> string(1) "1" ["in_slider"]=> string(1) "1" ["url"]=> string(59) "Harpa_Casual_th_Sleeve_Floral_Print_Womens_Multicolor_Top_1" ["virtual_products"]=> string(0) "" ["brand_id"]=> string(1) "3" ["position"]=> string(1) "2" ["vendor_id"]=> string(1) "0" ["title"]=> string(61) "Harpa Casual 3/4th Sleeve Floral Print Women's Multicolor Top" ["description"]=> string(82) "

following details occuered under product information in view page

**Comment by kirilkirkov** [comment]
@aswinsasi  fixed - https://github.com/kirilkirkov/Ecommerce-CodeIgniter-Bootstrap/commit/1dd3662a4e122457c00a8bef7f10a609e6f90e1f

**Comment by aswinsasi** [comment]
Thank you sir
