### ISSUE TITLE
js and csd not load 

### ISSUE THREAD

**Issue by aswinsasi** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#152]
What am I trying to do..
..What's happening 
while localhost/shop alter as localhost...paste directly without folder 
no change made to .htaccess and base url set as localhost on bnly
help mee

**Comment by kirilkirkov** [comment]
@aswinsasi Do you read explanation after installation steps?

**Comment by aswinsasi** [comment]
Yes sir...and its run properly on my localserver...i placed all files in
shop/... folder...its run properly in localserver...

But now in hosting i place directly the files in pubic_html without parent
folder shop/.. and change base_url as http://mywebbsitename/.

When website load the css and js is not working ..

how to manage it...

**Comment by kirilkirkov** [comment]
@aswinsasi return .htaccess file to the initial state

**Comment by aswinsasi** [comment]
return .htaccess file to the initial state...
Means

**Comment by aswinsasi** [comment]
...can u explain how to return .htaccess file...

**Comment by aswinsasi** [comment]
sir
kindly explain  how to return .htaccess file to the initial state.....

**Comment by kirilkirkov** [comment]
sir :1st_place_medal: 

RewriteEngine on
RewriteBase /
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php?/$1 [L]

**Comment by kirilkirkov** [comment]
:D
