### ISSUE TITLE
A PHP Error was encountered

### ISSUE THREAD

**Issue by ronniengoda** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#153]
A PHP Error was encountered
Severity: 8192

Message: strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior

Filename: MX/Router.php

Line Number: 239

Backtrace:

File: C:\xampp\htdocs\bomasara\application\third_party\MX\Router.php
Line: 239
Function: strpos

File: C:\xampp\htdocs\bomasara\application\third_party\MX\Router.php
Line: 101
Function: _set_default_controller

File: C:\xampp\htdocs\bomasara\application\third_party\MX\Router.php
Line: 68
Function: _set_default_controller

File: C:\xampp\htdocs\bomasara\index.php
Line: 292
Function: require_once

**Comment by kirilkirkov** [comment]
@ronniengoda where do you see this error?

**Comment by ronniengoda** [comment]
its at the top of every page....

**Comment by kirilkirkov** [comment]
@ronniengoda which version is of your php ?

**Comment by ronniengoda** [comment]
php version 7.3

**Comment by tru247** [comment]
Hi. I have also encountered the error. Am using PHP 7.3.0 How can this be solved?

**Severity: 8192**

Message: strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior

Filename: MX/Router.php

Line Number: 239

**Comment by kirilkirkov** [comment]
@tru247  @ronniengoda  Can you try with this fix - https://github.com/kirilkirkov/Ecommerce-CodeIgniter-Bootstrap/commit/71f9aab99b2257994ed0208de6863da1d28151f8

**Comment by kirilkirkov** [comment]
@ronniengoda  is it ok now?

**Comment by ronniengoda** [comment]
Yeah thanks alot...
