### ISSUE TITLE
order cannot be processed 

### ISSUE THREAD

**Issue by Kimson11** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#154]
am getting this when ever i tried to process and other
Error with status change. Please check logs!

**Comment by kirilkirkov** [comment]
Try to update with last version of system.  https://github.com/kirilkirkov/Ecommerce-CodeIgniter-Bootstrap/commit/37d0b8a6c03523be02d74b7f8b4f057a8d6f9b7e @Kimson11

**Comment by kirilkirkov** [comment]
@Kimson11 is it ok now?

**Comment by Kimson11** [comment]
yes
