### ISSUE TITLE
javascript map error

### ISSUE THREAD

**Issue by aswinsasi** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#155]
sir
when i add google map co-ordinate and api key in google map in admin pannel it will work properly...but in front end contact page the  map will load first time and then showing following error

Oops! Something went wrong.
This page didn't load Google Maps correctly. See the JavaScript console for technical details.

what to do sir

**Comment by kirilkirkov** [comment]
@aswinsasi give me the message from console log

**Comment by kirilkirkov** [comment]
@aswinsasi ?

**Comment by aswinsasi** [comment]
Sir I replace autoloader with php mailer
