### ISSUE TITLE
vendors_orders table not found

### ISSUE THREAD

**Issue by senjoy11** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#156]
What am I trying to register then login from vendor side..when logging in vendors_orders not found...database issue
![ecomm error](https://user-images.githubusercontent.com/41966981/54199414-dcdeb980-44ee-11e9-998d-ddf50d8a7f78.png)

..What's happening

**Comment by kirilkirkov** [comment]
@senjoy11 
Create your missing table: 

`CREATE TABLE `vendors_orders` (
  `id` int(10) UNSIGNED NOT NULL,
  `order_id` int(11) NOT NULL,
  `products` text NOT NULL,
  `date` int(10) UNSIGNED NOT NULL,
  `referrer` varchar(255) NOT NULL,
  `clean_referrer` varchar(255) NOT NULL,
  `payment_type` varchar(255) NOT NULL,
  `paypal_status` varchar(10) DEFAULT NULL,
  `processed` tinyint(1) NOT NULL DEFAULT '0',
  `viewed` tinyint(1) NOT NULL DEFAULT '0',
  `confirmed` tinyint(1) NOT NULL DEFAULT '0',
  `discount_code` varchar(20) NOT NULL,
  `vendor_id` int(10) UNSIGNED NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

ALTER TABLE `vendors_orders`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `vendors_orders`
MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;`

**Comment by aswinsasi** [comment]
Sir how to setup sendmail.php for a hosted one...can u show the setup for
cpanel sendmail.php config

**Comment by kirilkirkov** [comment]
@aswinsasi  Find mail settings in your cpanel.
This is your settings file application/libraries/SendMail.php (__constructor)

**Comment by aswinsasi** [comment]
K sir...but i do this in localhost i use smtp.gmail.com and succesfully
work for me..but in cpanel its not work proper

**Comment by aswinsasi** [comment]
Here is the screenshot

**Comment by aswinsasi** [comment]
Screenshot can u help how to setup it properly
