### ISSUE TITLE
Php mailer not sent mails 

### ISSUE THREAD

**Issue by aswinsasi** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#158]
Sir,
In public html the phpmailer is not working there is no error is shown but mail dorsnt sent...the same is run on localhost properly...i change the host usrrname,password and port in public html with my cpanel details..but not working...

What am I trying to do..
..What's happening

**Comment by kirilkirkov** [comment]
@aswinsasi uncomment line 15 from application/libraries/SendMail.php
		// $this->mail->SMTPDebug = 2; 
enable error logs from - application/config/config.php  $config['log_threshold'] = 1; 
and check errors in application/logs/ folder.

**Comment by aswinsasi** [comment]
K sir let's check it out.

**Comment by aswinsasi** [comment]
sir the following error is occuerd inside log errror...when i sent submit
order....mail cannt been sent...

<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2019-03-22 04:12:48 --> Severity: Warning --> ini_set() has
been disabled for security reasons
/home/cartmein/public_html/shop/system/core/CodeIgniter.php 245
ERROR - 2019-03-22 04:12:48 --> Severity: Warning --> ini_set() has
been disabled for security reasons
/home/cartmein/public_html/shop/system/core/CodeIgniter.php 278
ERROR - 2019-03-22 04:12:48 --> Severity: Warning --> ini_set() has
been disabled for security reasons
/home/cartmein/public_html/shop/system/libraries/Session/Session.php
282
ERROR - 2019-03-22 04:12:48 --> Severity: Warning --> ini_set() has
been disabled for security reasons
/home/cartmein/public_html/shop/system/libraries/Session/Session.php
304
ERROR - 2019-03-22 04:12:48 --> Severity: Warning --> ini_set() has
been disabled for security reasons
/home/cartmein/public_html/shop/system/libraries/Session/Session.php
314
ERROR - 2019-03-22 04:12:48 --> Severity: Warning --> ini_set() has
been disabled for security reasons
/home/cartmein/public_html/shop/system/libraries/Session/Session.php
315
ERROR - 2019-03-22 04:12:48 --> Severity: Warning --> ini_set() has
been disabled for security reasons
/home/cartmein/public_html/shop/system/libraries/Session/Session.php
316
ERROR - 2019-03-22 04:12:48 --> Severity: Warning --> ini_set() has
been disabled for security reasons
/home/cartmein/public_html/shop/system/libraries/Session/Session.php
317
ERROR - 2019-03-22 04:12:48 --> Severity: Warning --> ini_set() has
been disabled for security reasons
/home/cartmein/public_html/shop/system/libraries/Session/Session.php
348
ERROR - 2019-03-22 04:12:51 --> Severity: Warning --> ini_set() has
been disabled for security reasons
/home/cartmein/public_html/shop/system/core/CodeIgniter.php 245
ERROR - 2019-03-22 04:12:51 --> Severity: Warning --> ini_set() has
been disabled for security reasons
/home/cartmein/public_html/shop/system/core/CodeIgniter.php 278
ERROR - 2019-03-22 04:12:51 --> Severity: Warning --> ini_set() has
been disabled for security reasons
/home/cartmein/public_html/shop/system/core/CodeIgniter.php 245
ERROR - 2019-03-22 04:12:51 --> Severity: Warning --> ini_set() has
been disabled for security reasons
/home/cartmein/public_html/shop/system/core/CodeIgniter.php 278
ERROR - 2019-03-22 04:12:51 --> Severity: Warning --> ini_set() has
been disabled for security reasons
/home/cartmein/public_html/shop/system/libraries/Session/Session.php
282
ERROR - 2019-03-22 04:12:51 --> Severity: Warning --> ini_set() has
been disabled for security reasons
/home/cartmein/public_html/shop/system/libraries/Session/Session.php
304
ERROR - 2019-03-22 04:12:51 --> Severity: Warning --> ini_set() has
been disabled for security reasons
/home/cartmein/public_html/shop/system/libraries/Session/Session.php
314
ERROR - 2019-03-22 04:12:51 --> Severity: Warning --> ini_set() has
been disabled for security reasons
/home/cartmein/public_html/shop/system/libraries/Session/Session.php
315
ERROR - 2019-03-22 04:12:51 --> Severity: Warning --> ini_set() has
been disabled for security reasons
/home/cartmein/public_html/shop/system/libraries/Session/Session.php
316
ERROR - 2019-03-22 04:12:51 --> Severity: Warning --> ini_set() has
been disabled for security reasons
/home/cartmein/public_html/shop/system/libraries/Session/Session.php
317
ERROR - 2019-03-22 04:12:51 --> Severity: Warning --> ini_set() has
been disabled for security reasons
/home/cartmein/public_html/shop/system/libraries/Session/Session.php
348
ERROR - 2019-03-22 04:12:51 --> Severity: Warning --> ini_set() has
been disabled for security reasons
/home/cartmein/public_html/shop/system/libraries/Session/Session.php
282
ERROR - 2019-03-22 04:12:51 --> Severity: Warning --> ini_set() has
been disabled for security reasons
/home/cartmein/public_html/shop/system/libraries/Session/Session.php
304
ERROR - 2019-03-22 04:12:51 --> Severity: Warning --> ini_set() has
been disabled for security reasons
/home/cartmein/public_html/shop/system/libraries/Session/Session.php
314
ERROR - 2019-03-22 04:12:51 --> Severity: Warning --> ini_set() has
been disabled for security reasons
/home/cartmein/public_html/shop/system/libraries/Session/Session.php
315
ERROR - 2019-03-22 04:12:51 --> Severity: Warning --> ini_set() has
been disabled for security reasons
/home/cartmein/public_html/shop/system/libraries/Session/Session.php
316
ERROR - 2019-03-22 04:12:51 --> Severity: Warning --> ini_set() has
been disabled for security reasons
/home/cartmein/public_html/shop/system/libraries/Session/Session.php
317
ERROR - 2019-03-22 04:12:51 --> Severity: Warning --> ini_set() has
been disabled for security reasons
/home/cartmein/public_html/shop/system/libraries/Session/Session.php
348

**Comment by kirilkirkov** [comment]
@aswinsasi enable usage of ini_set .
https://www.google.com/search?client=ubuntu&channel=fs&q=Enable+ini_set+usage&ie=utf-8&oe=utf-8
