### ISSUE TITLE
php log error wehn sent mail

### ISSUE THREAD

**Issue by aswinsasi** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#160]
What am I trying to do..
<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2019-03-22 04:12:48 --> Severity: Warning --> ini_set() has been disabled for security reasons /home/cartmein/public_html/shop/system/core/CodeIgniter.php 245
ERROR - 2019-03-22 04:12:48 --> Severity: Warning --> ini_set() has been disabled for security reasons /home/cartmein/public_html/shop/system/core/CodeIgniter.php 278
ERROR - 2019-03-22 04:12:48 --> Severity: Warning --> ini_set() has been disabled for security reasons /home/cartmein/public_html/shop/system/libraries/Session/Session.php 282
ERROR - 2019-03-22 04:12:48 --> Severity: Warning --> ini_set() has been disabled for security reasons /home/cartmein/public_html/shop/system/libraries/Session/Session.php 304
ERROR - 2019-03-22 04:12:48 --> Severity: Warning --> ini_set() has been disabled for security reasons /home/cartmein/public_html/shop/system/libraries/Session/Session.php 314
ERROR - 2019-03-22 04:12:48 --> Severity: Warning --> ini_set() has been disabled for security reasons /home/cartmein/public_html/shop/system/libraries/Session/Session.php 315
ERROR - 2019-03-22 04:12:48 --> Severity: Warning --> ini_set() has been disabled for security reasons /home/cartmein/public_html/shop/system/libraries/Session/Session.php 316
ERROR - 2019-03-22 04:12:48 --> Severity: Warning --> ini_set() has been disabled for security reasons /home/cartmein/public_html/shop/system/libraries/Session/Session.php 317
ERROR - 2019-03-22 04:12:48 --> Severity: Warning --> ini_set() has been disabled for security reasons /home/cartmein/public_html/shop/system/libraries/Session/Session.php 348
ERROR - 2019-03-22 04:12:51 --> Severity: Warning --> ini_set() has been disabled for security reasons /home/cartmein/public_html/shop/system/core/CodeIgniter.php 245
ERROR - 2019-03-22 04:12:51 --> Severity: Warning --> ini_set() has been disabled for security reasons /home/cartmein/public_html/shop/system/core/CodeIgniter.php 278
ERROR - 2019-03-22 04:12:51 --> Severity: Warning --> ini_set() has been disabled for security reasons /home/cartmein/public_html/shop/system/core/CodeIgniter.php 245
ERROR - 2019-03-22 04:12:51 --> Severity: Warning --> ini_set() has been disabled for security reasons /home/cartmein/public_html/shop/system/core/CodeIgniter.php 278
ERROR - 2019-03-22 04:12:51 --> Severity: Warning --> ini_set() has been disabled for security reasons /home/cartmein/public_html/shop/system/libraries/Session/Session.php 282
ERROR - 2019-03-22 04:12:51 --> Severity: Warning --> ini_set() has been disabled for security reasons /home/cartmein/public_html/shop/system/libraries/Session/Session.php 304
ERROR - 2019-03-22 04:12:51 --> Severity: Warning --> ini_set() has been disabled for security reasons /home/cartmein/public_html/shop/system/libraries/Session/Session.php 314
ERROR - 2019-03-22 04:12:51 --> Severity: Warning --> ini_set() has been disabled for security reasons /home/cartmein/public_html/shop/system/libraries/Session/Session.php 315
ERROR - 2019-03-22 04:12:51 --> Severity: Warning --> ini_set() has been disabled for security reasons /home/cartmein/public_html/shop/system/libraries/Session/Session.php 316
ERROR - 2019-03-22 04:12:51 --> Severity: Warning --> ini_set() has been disabled for security reasons /home/cartmein/public_html/shop/system/libraries/Session/Session.php 317
ERROR - 2019-03-22 04:12:51 --> Severity: Warning --> ini_set() has been disabled for security reasons /home/cartmein/public_html/shop/system/libraries/Session/Session.php 348
ERROR - 2019-03-22 04:12:51 --> Severity: Warning --> ini_set() has been disabled for security reasons /home/cartmein/public_html/shop/system/libraries/Session/Session.php 282
ERROR - 2019-03-22 04:12:51 --> Severity: Warning --> ini_set() has been disabled for security reasons /home/cartmein/public_html/shop/system/libraries/Session/Session.php 304
ERROR - 2019-03-22 04:12:51 --> Severity: Warning --> ini_set() has been disabled for security reasons /home/cartmein/public_html/shop/system/libraries/Session/Session.php 314
ERROR - 2019-03-22 04:12:51 --> Severity: Warning --> ini_set() has been disabled for security reasons /home/cartmein/public_html/shop/system/libraries/Session/Session.php 315
ERROR - 2019-03-22 04:12:51 --> Severity: Warning --> ini_set() has been disabled for security reasons /home/cartmein/public_html/shop/system/libraries/Session/Session.php 316
ERROR - 2019-03-22 04:12:51 --> Severity: Warning --> ini_set() has been disabled for security reasons /home/cartmein/public_html/shop/system/libraries/Session/Session.php 317
ERROR - 2019-03-22 04:12:51 --> Severity: Warning --> ini_set() has been disabled for security reasons /home/cartmein/public_html/shop/system/libraries/Session/Session.php 348
ERROR - 2019-03-22 04:12:51 --> Severity: Warning --> ini_set() has been disabled for security reasons /home/cartmein/public_html/shop/system/core/CodeIgniter.php 245
ERROR - 2019-03-22 04:12:51 --> Severity: Warning --> ini_set() has been disabled for security reasons /home/cartmein/public_html/shop/system/core/CodeIgniter.php 278

following log error is occuerd when sent mail

**Comment by kirilkirkov** [comment]
Referer  https://github.com/kirilkirkov/Ecommerce-CodeIgniter-Bootstrap/issues/158
