### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by saeedisfahani** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#161]
hi
I try to adding web font to my own template but get 404 error on web font request.
I load local font-awsome files in my CSS file via @font but not working.

how can I use font-awsome icons?

**Comment by kirilkirkov** [comment]
@saeedisfahani load from cdn or create your urls like this -  base_url('assets/fonts/font.ttf')  where real directory is - application/views/templates/yourtemplate/fonts/font.ttf
