### ISSUE TITLE
"Out Of Stock" products still can be added to the cart

### ISSUE THREAD

**Issue by studuino** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#163]
Hi,
Product with "Out Of Stock" condition are having buttons like "Buy Now" or "Add To Cart" in home page product listing and in Slider.
would it be better to show "product is out of stock" instead as in view_product.

Thanks

**Comment by kirilkirkov** [comment]
@studuino 
This bug if fixed with this commit - https://github.com/kirilkirkov/Ecommerce-CodeIgniter-Bootstrap/commit/0e92c509dc4136779a573853c74848862774d748

I add "Hide buy button if product is shown but is out of stock" in administration Settings to hide it if you want. You must update the code and insert new record in value_store table in database.

**Comment by studuino** [comment]
Hi 
After the code and value_store(db) update,
(1) when "Hide buy button if product is shown but is out of stock" switch is on, there's no buy button in not only Out of stock products but in stock products as well.
![image](https://user-images.githubusercontent.com/2291009/81513014-2fae3e00-934b-11ea-9dfa-27dc128d0c0b.png)

![image](https://user-images.githubusercontent.com/2291009/81513164-4c974100-934c-11ea-855b-b7412619ce19.png)


(2) With the BUY NOW in slider, out of stock products still can be bought.

(3) almost all the products in product listings disappeared (11 out of 13 in-stock products)
Out of stock products appear correctly.
![image](https://user-images.githubusercontent.com/2291009/81513048-81ef5f00-934b-11ea-9176-9ebec1ca2ee2.png)

**Comment by kirilkirkov** [comment]
@studuino 
I fixed the slider.

**Comment by studuino** [comment]
@kirilkirkov 
Thanks a lot for the update. We appreciate your quick actions.
One finding is that when products(in-stock or out-of-stock) are in slider, they do not appear in product listing(home page).

**Comment by kirilkirkov** [comment]
@studuino  Yes , this is a desired behavior to avoid duplication.
You can easy change it in  the Public_model query

**Comment by studuino** [comment]
@kirilkirkov 
Thank you very much for the information.
We just found out there's a switch for that.
![image](https://user-images.githubusercontent.com/2291009/81610321-5332c080-93ff-11ea-8ba9-f6154efd046b.png)
Works just perfect now.
Cheers.
