### ISSUE TITLE
Both "Buy Now" and "Add to Shopping Cart" buttons go to shopping cart

### ISSUE THREAD

**Issue by studuino** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#164]
Both buttons go to shopping cart.
And either button is clicked loading animation on both buttons and go to shopping cart.
![image](https://user-images.githubusercontent.com/2291009/81468309-a1c83b00-9204-11ea-8a22-46519beaf90f.png)

I expect "Add to Shopping Cart" not be directed to shopping cart(before checkout)
but just does the job in the background.

Thanks

**Comment by kirilkirkov** [comment]
@studuino 
The platform has this option but it is not added by default.
I add option in administration settings - "Do not open shopping cart after add product to it" , there you can choose how to work.
Update your source and records to database from the commit below.


https://github.com/kirilkirkov/Ecommerce-CodeIgniter-Bootstrap/commit/08e751c40e1450b50bc798f6e26b7d934eb1cfaa
