### ISSUE TITLE
I'm having issues after installation, why did you downgraded to 3.1.8 I want to use CI 3.1.11 any issues with that?

### ISSUE THREAD

**Issue by kingblizzy** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#165]
I'm having issues after installation, why did you downgraded to 3.1.8 I want to use CI 3.1.11 any issues with that?

**Comment by kirilkirkov** [comment]
@kingblizzy 

I don't remember what the reason was.
I update it now with current last version 3.1.11 and it seems that work fine. If have some problems i am available.

https://github.com/kirilkirkov/Ecommerce-CodeIgniter-Bootstrap/commit/b1f51427dcd1efbfd7b8001db0ba6d34b8cccb4d
