### ISSUE TITLE
error installing 

### ISSUE THREAD

**Issue by mane06** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#166]
What am I trying to do..
..What's happening 
Hello when I add the system to my server and open the domain I have this problem 

Warning: mkdir(): Permission denied in /var/www/pruebas.tecnotop.online/htdocs/system/core/Log.php on line 131
A PHP Error was encountered
Severity: Warning

Message: mkdir(): Permission denied

Filename: core/Log.php

Line Number: 131

Backtrace:

File: /var/www/pruebas.tecnotop.online/htdocs/index.php
Line: 292
Function: require_once

An uncaught Exception was encountered
Type: Error

Message: Call to undefined function is_countable()

Filename: /var/www/pruebas.tecnotop.online/htdocs/application/core/MY_Controller.php

Line Number: 68

Backtrace:

File: /var/www/pruebas.tecnotop.online/htdocs/application/core/MY_Controller.php
Line: 29
Function: loadVars

File: /var/www/pruebas.tecnotop.online/htdocs/application/controllers/Home.php
Line: 39
Function: render

File: /var/www/pruebas.tecnotop.online/htdocs/index.php
Line: 292
Function: require_once

Can you help me please ?

**Comment by kirilkirkov** [comment]
@mane06 
This commit will fix your error - 
https://github.com/kirilkirkov/Ecommerce-CodeIgniter-Bootstrap/commit/3e0deac414b1eed4a89cfdd1d11503e43c839a01

Also check permissions of your logs directory in application/
