### ISSUE TITLE
Admin Settings Error

### ISSUE THREAD

**Issue by mykienesh** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#167]
Hi @kirilkirkov Im trying to change the settings in the admin dashboard and Im receiving the error below;

A PHP Error was encountered
Severity: Error

Message: Call to undefined function is_countable()

Filename: settings/Settings.php

Line Number: 55

Backtrace:

![image](https://user-images.githubusercontent.com/40571754/81735407-af4c2200-949d-11ea-9ddc-60564ce9feeb.png)

**Comment by kirilkirkov** [comment]
@mykienesh 
Hello. I fixed it - https://github.com/kirilkirkov/Ecommerce-CodeIgniter-Bootstrap/commit/6679aeda5a27b1514c67362aa63eb8d8ff383749
Update your code
