### ISSUE TITLE
Installation Bug

### ISSUE THREAD

**Issue by Coco0185** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#168]
Hi , 

I am installing on the root  port 81 , Ive modify the config.php,database.php and i've also remove the  "RewriteBase /" line from the .htaccess file but i still have issues
see the screenshot below 
![image](https://user-images.githubusercontent.com/65602241/82323021-b90ee180-99d7-11ea-8c79-81548da3298f.png)

Here is my config.php modify file : 

![image](https://user-images.githubusercontent.com/65602241/82323190-f7a49c00-99d7-11ea-9052-daf4450eabdb.png)

Here is my database.php modify file :

![image](https://user-images.githubusercontent.com/65602241/82323309-2a4e9480-99d8-11ea-9a47-223b442f228f.png)

Thank you for your work and for your help :)

**Comment by kirilkirkov** [comment]
@Coco0185 
Fixed with that commit - https://github.com/kirilkirkov/Ecommerce-CodeIgniter-Bootstrap/commit/90f202f2beb67ff798125e1308f2f885a645372c
