### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by collinski001** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#170]
the following error occurred during installation

A PHP Error was encountered
Severity: Warning

Message: mysqli::real_connect(): (HY000/1045): Access denied for user 'root'@'localhost' (using password: YES)

Filename: mysqli/mysqli_driver.php

Line Number: 203

Backtrace:

File: C:\xampp\htdocs\Ecommerce-CodeIgniter-Bootstrap-master\application\third_party\MX\Loader.php
Line: 109
Function: DB

File: C:\xampp\htdocs\Ecommerce-CodeIgniter-Bootstrap-master\application\third_party\MX\Loader.php
Line: 65
Function: initialize

File: C:\xampp\htdocs\Ecommerce-CodeIgniter-Bootstrap-master\application\third_party\MX\Base.php
Line: 55
Function: __construct

File: C:\xampp\htdocs\Ecommerce-CodeIgniter-Bootstrap-master\application\third_party\MX\Base.php
Line: 60
Function: __construct

File: C:\xampp\htdocs\Ecommerce-CodeIgniter-Bootstrap-master\application\third_party\MX\Controller.php
Line: 4
Function: require

File: C:\xampp\htdocs\Ecommerce-CodeIgniter-Bootstrap-master\application\third_party\MX\Modules.php
Line: 123
Function: include_once

File: C:\xampp\htdocs\Ecommerce-CodeIgniter-Bootstrap-master\application\core\MY_Controller.php
Line: 4
Function: spl_autoload_call

File: C:\xampp\htdocs\Ecommerce-CodeIgniter-Bootstrap-master\index.php
Line: 292
Function: require_once

A Database Error Occurred
Unable to connect to your database server using the provided settings.

Filename: C:/xampp/htdocs/Ecommerce-CodeIgniter-Bootstrap-master/application/third_party/MX/Base.php

Line Number: 55

**Comment by kirilkirkov** [comment]
@collinski001 
You password for mysql database is wrong. 
Set up right configuration in application/config/database.php

**Comment by collinski001** [comment]
which password should I use
