### ISSUE TITLE
Error adding products from publish product page in admin and french translation is not working

### ISSUE THREAD

**Issue by Coco0185** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#171]
What am I trying to do :

adding products from publish product page in admin and french translation is not working

..What's happening :

An uncaught Exception was encountered

Type: Error

Message: Call to undefined function mb_ereg_replace()

Filename: C:\MAMP\htdocs\application\helpers\except_letters_helper.php

Line Number: 9

Backtrace:

File: C:\MAMP\htdocs\application\modules\admin\models\Products_model.php
Line: 154
Function: except_letters

File: C:\MAMP\htdocs\application\modules\admin\controllers\ecommerce\Publish.php
Line: 39
Function: setProduct

File: C:\MAMP\htdocs\index.php
Line: 292
Function: require_once

About transaltion I ve modify and save  but it doesnt work :

![image](https://user-images.githubusercontent.com/65602241/82815424-75b1e880-9e99-11ea-8f9a-5b3fedbe6772.png)
![image](https://user-images.githubusercontent.com/65602241/82815510-9f6b0f80-9e99-11ea-847a-c20dbceb1712.png)

**Comment by kirilkirkov** [comment]
@Coco0185 
Which version of php you use? And did you have enabled mbstring php extension (by default is not enabled)?

**Comment by Coco0185** [comment]
Hi , 

I am using php 7.4.1:

![image](https://user-images.githubusercontent.com/65602241/82865829-fae3de80-9f27-11ea-9654-844a4b8ee7f1.png)
i didn't enable mbstring extension.
How can I enable it?

Thank you for your answer

**Comment by Coco0185** [comment]
I've found it in my phpinfo page:
![image](https://user-images.githubusercontent.com/65602241/82867516-4d72ca00-9f2b-11ea-8105-5812d194f2ba.png)

I guess it is enable

**Comment by Coco0185** [comment]
below a full screenshot of the mbstring 

![image](https://user-images.githubusercontent.com/65602241/82867676-8e6ade80-9f2b-11ea-8f99-abadc6bc3e8f.png)

**Comment by kirilkirkov** [comment]
@Coco0185 Check your configurations or replace this function with another one in the  application/helpers/except_letters_helper.php.
This is not a bug in the platform.
