### ISSUE TITLE
I can not install it

### ISSUE THREAD

**Issue by alansystem** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#172]
Maybe I'm the only person who can't install the project, I'm using XAMPP, I pointed to the database, I modified the base_url, exactly as the explanation, including I already work with codeigniter, and even then it didn't work, follow the prints.

![image](https://user-images.githubusercontent.com/308702/83218732-e9c3e900-a144-11ea-9cda-e8d9c5dd651d.png)

![image](https://user-images.githubusercontent.com/308702/83218744-f47e7e00-a144-11ea-909d-d6da9875985d.png)

**Comment by kirilkirkov** [comment]
@alansystem  You must modify your .htaccess file to load resources :)

**Comment by kirilkirkov** [comment]
"must remove from .htaccess file "RewriteBase /" line because css and js files will not be loaded"
