### ISSUE TITLE
{Suggestion} Bootstrap 4 Support

### ISSUE THREAD

**Issue by VuBrian22** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#173]
Is this fully supported on Bootstrap 4 or do certain features work but others don't? I understand that it currently say version 3.3.7.

**Comment by kirilkirkov** [comment]
@VuBrian22  Yes. Current version of bootstrap is v3.3.7.
To migrate to version 4 must rewrite the html of the templates.
