### ISSUE TITLE
templates are not loading

### ISSUE THREAD

**Issue by adityabarshilia** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#175]
the product templates are not showing. and a popup of  "No Results" shows when the home page is loaded. 
I'm an amateur. just need help regarding this.

**Comment by kirilkirkov** [comment]
@adityabarshilia 
Have you added products during the administration?

**Comment by adityabarshilia** [comment]
no, i don't think i did. only installed the project, did the config and database changes and run the project

**Comment by kirilkirkov** [comment]
@adityabarshilia 
You must add products from administration (/admin - url) to have something that show on homepage
