### ISSUE TITLE
admin page

### ISSUE THREAD

**Issue by boardgame1** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#177]
What am I trying to do..
When I go http://myshop.com:3545/admin
..What's happening 
show 'not found'

**Comment by kirilkirkov** [comment]
@boardgame1 Check if your .htaccess file is correct

**Comment by boardgame1** [comment]
I running on windows.
Is there additional setting?

**Comment by kirilkirkov** [comment]
@boardgame1 
No, if you use Apache and yours .htaccess file is loaded , application must work fine

**Comment by singhalpiyush12** [comment]
Hi, I am facing this similar issue. My .htaccess file is working fine but "http://localhost/SHOP/admin" gives 404

**Comment by kirilkirkov** [comment]
@singhalpiyush12  If you want to use the platform in subdirectory eg. "/SHOP", you must remove "RewriteBase /" line from .htaccess file.

**Comment by Ishtiaq6330** [comment]
I am facing same issue. I have checked .htaccess file, there is no line like "RewriteBase". Whenever i try to access "localhost/myshop/admin" it says 404 page not found
