### ISSUE TITLE
product detail issue some product shown the detail and some aren't in php 5.4

### ISSUE THREAD

**Issue by nauman22** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#178]
What am I trying to do is product detail issue some product shown the detail and some aren't in php 5.4 with xampp settings

if we replace applicaiton/helpers/except_letters_helper.php 
$onlyLetters = mb_ereg_replace('[^\\p{L}\s]', '', $string); 
to
 $onlyLetters = mb_ereg_replace('/[^\p{L}\s]/', '', $string);
then it works perfectly for each product detail link creation.
thank you
regards

**Comment by kirilkirkov** [comment]
@nauman22  but expression will not work
