### ISSUE TITLE
html tags saved on ckeditor does not render

### ISSUE THREAD

**Issue by rizalmart** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#179]
An html saved by ckeditor does not render on the html page. For example on Admin Settings > Contact Page.
if I saved `<p>Hello World</p>` using the text mode of ckeditor. It renders `<p>Hello World</p>` on the contact page as is, it does not render the `<p>` tags

**Comment by kirilkirkov** [comment]
@rizalmart 
Fix - https://github.com/kirilkirkov/Ecommerce-CodeIgniter-Bootstrap/commit/5e086da527515a7d34f7e2a14d3e0da743f77100
