### ISSUE TITLE
My Profile page issue

### ISSUE THREAD

**Issue by shoping-hue** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#183]
Greenlabel template some issues. 
My Profile page gives an error on the number of products and doesn't show product's photo. 

`A PHP Error was encountered
Severity: Notice

Message: Array to string conversion

Filename: greenlabel/user.php

Line Number: 60

Backtrace:`

![error](https://user-images.githubusercontent.com/67699287/86258944-134cb600-bbc4-11ea-9e15-f6a9ef572bbc.JPG)

**Comment by kirilkirkov** [comment]
@shoping-hue 
Hello.
Checkout this commit  - https://github.com/kirilkirkov/Ecommerce-CodeIgniter-Bootstrap/commit/6fbedb63903515785f9271e90de91fe49c1f30cf
It must be okay now
