### ISSUE TITLE
Authorize.net

### ISSUE THREAD

**Issue by RomanFire** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#186]
I would like to use authorize.net as a payment gateway. could you guys add support for that or how would I go about adding it myself.

**Comment by kirilkirkov** [comment]
@RomanFire  You must integrate it

**Comment by RomanFire** [comment]
how much coffee would I have to buy ya so you could integrate it cause it would really help move my project along.

**Comment by kirilkirkov** [comment]
@RomanFire Sorry but i have no time now : ) . The platform is free and you can download it and modify how you want :)
