### ISSUE TITLE
Can't find way to add Paypal or any other payment Gateway

### ISSUE THREAD

**Issue by saintjk** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#188]
In the Checkout page, I can only find Cash on Delivery as the Option. I couldn't find any option in admin panel or code to enable the same.

Thanks in advance.

**Comment by RA666666** [comment]
hi how add payment gateway

**Comment by Grace-Endy** [comment]
Yeah, I also wonder how to do so?

**Comment by kirilkirkov** [comment]
@RA666666 @Grace-Endy 
You must read the documentation of Stripe and add the workflow to the Checkout Controller. You must add new payment_type to the checkout.php view for the template that you use. Then if this method is selected, you must write the code to be proccessed the payment.
