### ISSUE TITLE
Search functionality doesn't work

### ISSUE THREAD

**Issue by Grace-Endy** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#190]
When I run the project, the pages display normally, but the search functionality doesn't work.  When I try to search a query,
the url changes and becomes like this: http://localhost/work/?category=&in_stock=&search_in_title=sear&order_new=&order_price=&order_procurement=&brand_id=&quantity_more=&added_after=&added_before=&search_in_body=&price_from=&price_to=
But, nothing appears on the rest of the page.

**Comment by kirilkirkov** [comment]
@Grace-Endy It will be better to use virtual host instead of subdirectory of the platform. I have made tests and i see that it works fine. Are you sure that you have products with name that include "sear"

**Comment by kirilkirkov** [comment]
@Grace-Endy I hope everything is fine now?

**Comment by Grace-Endy** [comment]
No, I cloned the project and tried on multiple computers,  I added a bunch of products,  brands, categories,  and so on. Still the same issue.

**Comment by kirilkirkov** [comment]
@Grace-Endy Did you try to add virtual host for the project? Because i see that you use it from subdirectory?

**Comment by Grace-Endy** [comment]
Subdirectory? What do you really mean?

Le lun. 17 août 2020 12:35 AM, Kiril Kirkov <notifications@github.com> a
écrit :

**Comment by kirilkirkov** [comment]
http://domain.com/subdirectory :) 

Install the platform in virtual host, i mean - shop.domain.com (for example)

**Comment by Grace-Endy** [comment]
Oh okay,  I did so yesterday.  I'm gonna test it this morning to see if the
functionalities work.

I was wondering how could I add stripe and payment via credit cart.
Do you have any idea about how?

Le mar. 18 août 2020 7:54 AM, Kiril Kirkov <notifications@github.com> a
écrit :

**Comment by kirilkirkov** [comment]
@Grace-Endy Yeah, you must write little piece of code :) Check the stripe documentation and integrate it.
