### ISSUE TITLE
The filter category doesn't function

### ISSUE THREAD

**Issue by Grace-Endy** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#191]
Even though I posted a lot of products, and created some categories in the admin dashboard, but when I go to the store and try to filter the products, it shows "No results". What should I do in this case?

**Comment by kirilkirkov** [comment]
@Grace-Endy  I have checked and it works. Are you sure that you are choose different categories in your product? If you edit an product you have option to select category for that product.
