### ISSUE TITLE
comments add

### ISSUE THREAD

**Issue by RA666666** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#194]
you created awesome  project....
congratulations.... to you.
blog comments and products comment add  have you  in idea??

**Comment by RA666666** [comment]
contacts page does not work brother....

**Comment by kirilkirkov** [comment]
@RA666666  Did you add your credentials into application/libraries/SendMail.php file? There you must set the smpt server that you want to use.

**Comment by RA666666** [comment]
thanks brother

**Comment by RA666666** [comment]
from submit how do work?

**Comment by kirilkirkov** [comment]
@RA666666 I am not sure that i understand you. When you submit contacts form and there is a message in the field, the email will be sended with the entered smtp server.
