### ISSUE TITLE
Add encryption mode for sensitive data fields

### ISSUE THREAD

**Issue by rizalmart** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#197]
This project is good however the weakness here is the data privacy and security. The customer's email, addresses, bank accounts, and phone number was stored clearly. I suggest that you must add an option to store the customers address and phone number encrypted. As a first line of defense againsts data leakage

**Comment by kirilkirkov** [comment]
The clients data will be encrypted in future
