### ISSUE TITLE
Product seo

### ISSUE THREAD

**Issue by Grace-Endy** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#198]
The meta tags(Using for seo) are only available for the home page, the contact page and so on. I wonder how can I add proper meta tags which would hold a product characteristics. Like, when you share a product link on facebook or on whatsapp, so that the product image, the title, and a short part of the product description appears. Please, how can I acheive this?

**Comment by kirilkirkov** [comment]
@Grace-Endy 
Which template you use? All products has individual title, description and keywords.
