### ISSUE TITLE
Need Help to change menu and submenu

### ISSUE THREAD

**Issue by infocodeart** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#199]
Need help to change main menu and sub menu like attached file.

please contact me on

infocodeart@yahoo.com
![urban](https://user-images.githubusercontent.com/60613989/91719037-37bc1300-ebb2-11ea-8f3c-561ddc1a266f.png)

**Comment by kirilkirkov** [comment]
@infocodeart 
The attached screenshot is not from this platform.
In the administration section on this platform you can add new categories and subcategories from url - "/admin" -> Shop Categories. In Parent select menu you can choose to which category you want to add subcategory.
