### ISSUE TITLE
Email functionnality in contact form doesn't work

### ISSUE THREAD

**Issue by Grace-Endy** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#200]
One more time, I would like to thank you for this awesome project. So I actually facing an issue with either the contact form and the order option. So, When a user fill the contact form and submit it, and when a user order a product, I don't reveive any notification on my email. Even If I configured the phpmailer(I added my email and password) and I also added my email in the admin dashboard. The project is actually hosted on a shared hosting service. What should I do in this case?

**Comment by kirilkirkov** [comment]
@Grace-Endy I dont know what a settings you are using. You must debug this

**Comment by Grace-Endy** [comment]
![email_configure](https://user-images.githubusercontent.com/42899690/92050080-c61acb00-ed51-11ea-8ba2-7aad26889943.JPG)
I use this config, the email and password are just examples

**Comment by kirilkirkov** [comment]
I can debug it here.

**Comment by Grace-Endy** [comment]
I don't know what the mistake is!

**Comment by Grace-Endy** [comment]
I mean, what part should I send to you sir?

**Comment by Grace-Endy** [comment]
Hello my friend. Please, could you show me an example of phpmailer configuration that I can use?
