### ISSUE TITLE
admin access

### ISSUE THREAD

**Issue by Ishtiaq6330** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#201]
i am unable to access the admin panel, can you please tell me the address for admin panel?
The project is in localhost(xamp). I am able to access the project like "localhost/myshop" but whenever i try to access "localhost/myshop/admin" it says "404 page not found".

**Comment by kirilkirkov** [comment]
@Ishtiaq6330  You must change yours .htaccess file to works. Create a subdomain of the platform and it will work with the current .htaccess configuration
