### ISSUE TITLE
Add Menu Submenu

### ISSUE THREAD

**Issue by riadapsis** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#203]
Hi, I am using the clothesshop template. Now I want to add Menu/ Submenu to the top. But can't find anything at admin panel. Do you please help me?

**Comment by kirilkirkov** [comment]
@riadapsis You can add only textual pages. Go to Administration -> Active pages, create new one and the give name for the main menu from TEXTUAL PAGES section in administration
