### ISSUE TITLE
By default new order admin-notification delivering to buyer mail

### ISSUE THREAD

**Issue by CodeProDevelopper** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#204]
This project is very helpful but I found one issue. After booking order the message( "Hello, you have new order. Can check it in /admin/orders")  is delivered to user, who buying the product. This mail is delivered to admin email but copy of this is also delivered to user email. Please Correct this.

**_public_html/application/controllers/Checkout.php_**

private function sendNotifications()
    {
        $users = $this->Public_model->getNotifyUsers();
        $myDomain = $this->config->item('base_url');
        if (!empty($users)) {
            foreach ($users as $user) {
                $this->sendmail->sendTo($user, 'Admin', 'New order in ' . $myDomain, 'Hello, you have new order. Can check it in /admin/orders');
            }
        }
    }

**_public_html/application/models/Public_model.php_**

public function getNotifyUsers()
    {
        $result1 = $this->db->query('SELECT email FROM users WHERE notify = 1');
        $arr1 = array();
        foreach ($result1->result_array() as $email_admin) {
            $arr1[] = $email_admin['email'];
        }
        return $arr1;
    }

**Comment by kirilkirkov** [comment]
@CodeProDevelopper  The users table is used only from administrators. Then administrator is marked with "notify" marker will receive notification message for new order. You can remove your notification marker from "/admin/adminusers", edit the admin and set "Notifications" field to 0

**Comment by CodeProDevelopper** [comment]
Thanks for your quick reply. I am happy to send notification to admin, So, I kept "Notification" field in "/admin/adminusers" to 1. 

But **my problem is that** When a NOT-AN-ADMIN user book a order and he himself receives a email ( "Hello, you have new order. Can check it in /admin/orders") .

**Comment by mzerbo98** [comment]
Hello, any solution to this ? Tried inspecting the code but everything seems OK up to the sendmail.sendto function, I placed some logs and the recipient value is normal. I think the problem is due to the addAdress function which could add the the client email since he also get a mail, I'm testing that

**Comment by mzerbo98** [comment]
So for anyone having this problem, it should be solved by adding 
$this->mail->clearAddresses();
at the beginning of the sendTo function

**Comment by kirilkirkov** [comment]
https://github.com/kirilkirkov/Ecommerce-CodeIgniter-Bootstrap/commit/f565e404f3264bc2c8581b89bdc9a51aec38f055

**Comment by CodeProDevelopper** [comment]
> So for anyone having this problem, it should be solved by adding
> $this->mail->clearAddresses();
> at the beginning of the sendTo function

thanks it helped
**$this->sendmail->mail->clearAddresses();**
adding this before sendTo function, Solved the problem
