### ISSUE TITLE
template errors

### ISSUE THREAD

**Issue by bpiltz** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#206]
the current templates cause this error:

```
Message: Undefined variable: image
Filename: _parts/header.php
Line Number: 13

Backtrace:
File: /var/www/codeigniter/application/views/templates/onepage/_parts/header.php
Line: 13
Function: _error_handler

File: /var/www/codeigniter/application/third_party/MX/Loader.php
Line: 355
Function: include

File: /var/www/codeigniter/application/third_party/MX/Loader.php
Line: 294
Function: _ci_load

File: /var/www/codeigniter/application/core/MY_Controller.php
Line: 49
Function: view


File: /var/www/codeigniter/application/controllers/Home.php
Line: 39
Function: render

File: /var/www/codeigniter/index.php
Line: 292
Function: require_once
http://localhost/codeigniter/assets/img/site-overview.png" /> 
```
caused by this: 
`<meta property="og:image" content="<?= !is_null($image) ? $image : base_url('assets/img/site-overview.png') ?>" />`
image is undefined it seems. I simply removed `!is_null($image) ? $image : ` now as I don't wanted to research where that image would come from. Maybe later ;-)

Also other template errors on greenlabel and onepager found around `$cartItems['array'] != null` which for example rather should be `!empty($cartItems['array'])`

Anyways nice project! Will look around.

**Comment by Dauli** [comment]
That was helpful @bpiltz , thanks.
And thanks @autor for this great work.

**Comment by kirilkirkov** [comment]
The notice is fixed  - https://github.com/kirilkirkov/Ecommerce-CodeIgniter-Bootstrap/commit/1b8542872f1d18e56a39319f26187c15a84c7753
