### ISSUE TITLE
How to get sub categorie name in home.php (redlabel)

### ISSUE THREAD

**Issue by c9chipheo** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#207]
I am trying to display sub categorie like this
![Screenshot 2020-10-13 235804](https://user-images.githubusercontent.com/40244731/95892045-1b65e580-0db0-11eb-96cc-5c94b56ba7ff.png)
How to get sub categorie from home.php? Many thanks

**Comment by kirilkirkov** [comment]
In the templates you have option for subcategories. You can change listing design in the html structure.
