### ISSUE TITLE
Errors After Adding product from Vendors

### ISSUE THREAD

**Issue by jeromesenyonga** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#210]
Hello,
I'm getting these errors when i add a product..

Errors
.........................................................................................................................................................................................................
A PHP Error was encountered
Severity: Notice

Message: Undefined index: brand_id

Filename: models/Products_model.php

Line Number: 34

Backtrace:

File: /home/herbalafrica/public_html/application/modules/vendor/models/Products_model.php
Line: 34
Function: _error_handler

File: /home/herbalafrica/public_html/application/modules/vendor/controllers/AddProduct.php
Line: 36
Function: setProduct

File: /home/herbalafrica/public_html/index.php
Line: 292
Function: require_once

Second Error
.................................................................................................................................................
A PHP Error was encountered
Severity: Warning

Message: Cannot modify header information - headers already sent by (output started at /home/herbalafrica/public_html/system/core/Exceptions.php:271)

Filename: helpers/url_helper.php

Line Number: 564

Backtrace:

File: /home/herbalafrica/public_html/application/modules/vendor/controllers/AddProduct.php
Line: 43
Function: redirect

File: /home/herbalafrica/public_html/index.php
Line: 292
Function: require_once

Kindly help out

**Comment by kirilkirkov** [comment]
@jeromesenyonga  
Its fixed - https://github.com/kirilkirkov/Ecommerce-CodeIgniter-Bootstrap/commit/cf1ceaa16a6ed5a32e9eea6fa62864dba99beac7
You can update this file from the repository.
