### ISSUE TITLE
Database Error on vendor logged in (me page)

### ISSUE THREAD

**Issue by bpiltz** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#211]
accessing (after having logged in successfully):

`http://localhost/vendor/me`

gives this error:
```
A Database Error Occurred
Error Number: 1064

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ASC' at line 1

SELECT YEAR(FROM_UNIXTIME(date)) as year, MONTH(FROM_UNIXTIME(date)) as month, COUNT(id) as num FROM vendors_orders WHERE vendor_id = 1 GROUP BY YEAR(FROM_UNIXTIME(date)), MONTH(FROM_UNIXTIME(date)) ASC

Filename: modules/vendor/models/Vendorprofile_model.php

Line Number: 48
```

The problem occurs on PHP Version 7.4.12 and mysql  Ver 8.0.22 for Linux on x86_64 (Source distribution)

With the exact same data in the database it is working fine with: 
PHP Version 7.3.24 and mysql  Ver 15.1 Distrib 5.5.65-MariaDB, for Linux (x86_64) using readline 5.1

**Comment by kirilkirkov** [comment]
@bpiltz You have no "ORDER BY" before the ASC

**Comment by bpiltz** [comment]
@kirilkirkov well that is original code from you. Otherwise I would not post it here ;-) No modification from my end on that. But I could debug it probably if you wish.

**Comment by bpiltz** [comment]
removed "ASC" now as there is no field within the clause meant to be used for ordering.

**Comment by kirilkirkov** [comment]
@bpiltz 
Pull the code. Now the query must works fine.
