### ISSUE TITLE
Code Assistance

### ISSUE THREAD

**Issue by mailantwi** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#212]
Hello, thank you very much for this project. I am trying to rewrite portions of it to include some features and and to port it to CI 4. But am finding it a little challenging knowing the actual code that gets the work done. Kindly assist. thanks.

**Comment by kirilkirkov** [comment]
@mailantwi 
Read the codeigniter documentation of CI4 and rewrite it to it if you want.

**Comment by mailantwi** [comment]
I have read it, but am finding it difficult understanding your code structure especially with the modules and third party.

**Comment by kirilkirkov** [comment]
@mailantwi 
its normal to have difference between CI3 and CI4, you must find some article in google how to migrate it.

**Comment by mailantwi** [comment]
It’s not the CI code base that I need assistance on but a walk through your controllers, models and views.
