### ISSUE TITLE
not reading css and javascript

### ISSUE THREAD

**Issue by Uzbekyt** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#214]
Hello! I did all the steps as you mentioned, but there is not line "RewriteBase /" in .htaccess file. Moreover, home page is loading without css and javascript, and if I click other links, they are not opening. Thanks
![Screen Shot 2020-11-20 at 3 21 18 AM](https://user-images.githubusercontent.com/67287513/99736277-91f8b000-2adf-11eb-9608-5fd75fdd2b6d.png)

**Comment by ghostwg** [comment]
the same

**Comment by kirilkirkov** [comment]
@Uzbekyt  Did you add your website url to the config.php file?

**Comment by bpiltz** [comment]
@Uzbekyt please check that htaccess is enabled in your virtual host. It fooled me quite a while in the beginning ;-)
