### ISSUE TITLE
Message: Required parameter $limit follows optional parameter $lang

### ISSUE THREAD

**Issue by akm1967** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#221]
What am I trying to do..
Click on Blog Menu
..What's happening
Getting bellow Error:
A PHP Error was encountered
Severity: 8192

Message: Required parameter $limit follows optional parameter $lang

Filename: models/Blog_model.php

Line Number: 34

**Comment by srkritfirm** [comment]
That's my problem 

A PHP Error was encountered
Severity: 8192

Message: Required parameter $slug follows optional parameter $limit

Filename: models/Genre_model.php

Line Number: 128
