### ISSUE TITLE
Php error

### ISSUE THREAD

**Issue by ugintl** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#224]
After setting up config.php and database.php files, I am getting following error.

![kirkov](https://user-images.githubusercontent.com/12570802/138857019-5da6cb68-326b-45de-a163-a0abed897c12.jpeg)

**Comment by kirilkirkov** [comment]
@ugintl 
Its fixed

**Comment by kirilkirkov** [comment]
@Nasreddine 
Try to update you code with git pull
Fix is in master branch
