### ISSUE TITLE
PHP Error - undefined variable url

### ISSUE THREAD

**Issue by carbon0021** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#225]
![Capture](https://user-images.githubusercontent.com/61119685/139422434-ab420e32-8bf1-4e34-aaf0-fc215d0886e6.PNG)

**Comment by samsul253** [comment]
Is there any solutions for it, I have same issue. Thank you.

**Comment by daniyalhussain32** [comment]
Hi, 
@samsul253, @carbon0021 
i have found the porblem. 

Actually, it's $uri not $url so in helper there is little mistake. Everything is not free sometime we need pay for it and the thing that we pay for such free apps is time.

What you need to do to solve the problem : go to system > helpers > url_helper
then on line 87 change $url to $uri
![Screenshot_50](https://user-images.githubusercontent.com/23362191/140526667-6eec11be-c454-4984-91be-1a2bc524d78b.png)

**Comment by ugintl** [comment]
@daniyalhussain32 good catch. I am seeing following error. Did you come around this one as well? I am using php 7.4.

`Deprecated: __autoload() is deprecated, use spl_autoload_register() instead in C:\laragon\etc\php\pear\PHPMailer\PHPMailerAutoload.php on line 45`

**Comment by kirilkirkov** [comment]
@daniyalhussain32 
that fix is uploaded with commit - https://github.com/kirilkirkov/Ecommerce-CodeIgniter-Bootstrap/commit/cf884e737b72743880abc8bb2aa4e681e5e88cac

@ugintl 
What a version of php you use?

**Comment by ugintl** [comment]
@kirilkirkov 7.4

**Comment by kirilkirkov** [comment]
@ugintl 
go to that file and change __autoload  to spl_autoload_register.
or downgrade your version
