### ISSUE TITLE
Sync vendor orders and admin orders

### ISSUE THREAD

**Issue by bpiltz** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#227]
In multi vendor mode each time an order is submitted it appears in the orders and the vendor_orders table. In the admin area the orders are listed then also but they are never processed. This seems confusing for us. I understand that we should have (maintain) both the way this is structured but I wonder what would be the best way to update also the order statues along with the vendor_order status? Both worlds seem pretty separated and on the first glance I do not see a proper way to load admin/Order_model and vendor/Order_model at the same time because both would be addressed by $this->Order_model if I am not mistaken from within one controller.

What is your suggestion how to deal with this @kirilkirkov?

**Comment by kirilkirkov** [comment]
Hello @bpiltz ,
you can pass the $orderId variable to the setVendorOrders method (in Checkout.php controller -> index()) and then save it to a new column in the database (which you need to create). In this way you can mark them as processed easily.
