### ISSUE TITLE
A Database Error Occurred. Error Number: 1146

### ISSUE THREAD

**Issue by jessicana** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#228]
I am sure about the database credentials but I get the below error. How can I fix that?
```
A Database Error Occurred
Error Number: 1146

Table 's1b.value_store' doesn't exist

SELECT value FROM value_store WHERE thekey = 'outOfStock' LIMIT 1

Filename: modules/admin/models/Home_admin_model.php

Line Number: 128
```
Could this error be linked to the first step: `Import database.sql to your mysql`?
What does the documentation mean by Importing database.sql to my mysql? Can you please elaborate more about this and how I can solve it?

**Comment by kirilkirkov** [comment]
@jessicana 
Your table value_store is missing. The database.sql file is the default structure of the platform, so you need to import this file to yours database and the website should work.

**Comment by jessicana** [comment]
Thanks! How can I import the table value_store file to the database?

**Comment by kirilkirkov** [comment]
This table exsits in the database,sql file. When you import this file, the table will exist
