### ISSUE TITLE
website only displays directory list

### ISSUE THREAD

**Issue by topcat30** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#230]
website only displays directory list

**Comment by kirilkirkov** [comment]
Hello @topcat30 
Did you have webserver (eg. apache or nginx), mod_rewrite eabled and php installed and enabled?

**Comment by adiljay05** [comment]
@kirilkirkov  Yes, Same issue with me. I have php 7.2 running on namecheap hosting.

**Comment by adiljay05** [comment]
> @kirilkirkov Yes, Same issue with me. I have php 7.2 running on namecheap hosting.

my domain is jawadadil.com with ssh enabled.

I'm giving this in base url. You can try visiting the URL. it will show you what I mean.

$config['base_url'] = defined('https://jawadadil.com/')?BASE_URL:'';

**Comment by kirilkirkov** [comment]
@adiljay05 
When i open your website, i didn't see **index.php** file. This file will start your shop ready to use. Make sure to add the .htaccess file and index.php file in the root directory of the project. You can also download the platform directly from github as .zip file and then upload it into your server and extract the .zip file there. This will list all needed files.

**Comment by kirilkirkov** [comment]
For the domain - https://jawadadil.com/codeigniter/ you need to edit the $config['base_url'] to  $config['base_url'] = 'https://jawadadil.com/codeigniter/';

**Comment by kirilkirkov** [comment]
Also check the github tutorial for the installation steps - https://github.com/kirilkirkov/Ecommerce-CodeIgniter-Bootstrap , there you can find how to install the online shop to directory and how to install it in the root directory  : )
