### ISSUE TITLE
Cannot load CSS and JavaScript files

### ISSUE THREAD

**Issue by adiljay05** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#231]
CSS and Javascript files are not found, I was able to run the application, But due to the lack of the files, the view is not making any sense. Here's the image from console.
<img width="651" alt="image" src="https://user-images.githubusercontent.com/51061044/173229622-69a933c5-5c34-4434-992e-4ee169223cc2.png">

Here's the image of my webpage.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/51061044/173229660-acd2a231-c9a5-4dc9-9ca4-e95dffd8ec10.png">

**Comment by kirilkirkov** [comment]
@adiljay05 
Please follow the instructions from the readme.md file - https://github.com/kirilkirkov/Ecommerce-CodeIgniter-Bootstrap


> Little explanation about the installation - if you paste installation of project in directory something like http://localhost/SHOP, you must set this directory to application/config/config.php - $config['base_url'] = 'http://localhost/SHOP'; and must remove from .htaccess file "RewriteBase /" line because css and js files will not be loaded! But you must know that the best way to install this platform is to set it in root http://localhost/ directory or if you want to be in other directory just set virtual host for this and point him to there. (example: http://shop.dev/ - point to localhost/shop directory). How to create virtual hosts you can read here: http://goo.gl/UvpYMG

>
