### ISSUE TITLE
checkout.pph error

### ISSUE THREAD

**Issue by ValeraT17** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#233]
What am I trying to do..
..What's happening 
An uncaught Exception was encountered
Type: Error

Message: Call to undefined method SendMail::clearAddresses()

Filename: C:\xampp\htdocs\Primedawn_Hardware\application\controllers\Checkout.php

Line Number: 72

Backtrace:

File: C:\xampp\htdocs\Primedawn_Hardware\application\controllers\Checkout.php
Line: 41
Function: sendNotifications

File: C:\xampp\htdocs\Primedawn_Hardware\index.php
Line: 292
Function: require_once

**Comment by kirilkirkov** [comment]
@ValeraT17 
This issue is fixed. Download/Refresh you code again
