### ISSUE TITLE
Adding RTL feature

### ISSUE THREAD

**Issue by MassaM-SDC** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#235]
I am trying to add Persian(FA) language to the templates to change the display direction from Right to Left.
Where can I add a condition to update the direction fro LTR to RTL in the header.php based on the language selection?

**Comment by kirilkirkov** [comment]
@MassaM-SDC 
You should write your custom logic in the header.php file. Maybe you will need to change the css styles. Currently the direction is default
