### ISSUE TITLE
Laravel ecommerce project

### ISSUE THREAD

**Issue by ugintl** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#238]
Why did you gave up on this project [Ecommerce Laravel Bootstrap](https://github.com/kirilkirkov/Ecommerce-Laravel-Bootstrap) Any specific reason?

**Comment by kirilkirkov** [comment]
@ugintl 
Currently the platform is ready for use. I archived it as I don't have enough time for its development.
