### ISSUE TITLE
Recommended db settings

### ISSUE THREAD

**Issue by ugintl** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#239]
What is the recommended db charset and collation for CI 3?

**Comment by surepeps** [comment]
@ugintl by default  charset comes with cl3 setting 
Check the following path "application/config/database.php"
But you can change it if you want just that for every tables must have charset utf8mb4 engine

**Comment by ugintl** [comment]
@surepeps Thanks. I have a CI 3 app which is using latin1_swedish_ci for database and utf8_general_ci for tables. Is it ok?

**Comment by kirilkirkov** [comment]
@ugintl 
utf8_general_ci is better encoding, so i suggest you to change the tables which are latin1_swedish_ci to utf8_general_ci
