### ISSUE TITLE
 problem with sql database

### ISSUE THREAD

**Issue by Dodi-3009** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#244]
Hi, I'm pretty new to this so I might have done something wrong.
I'm trying to use this script on altervista and I managed to load it, but once loaded I go to phpmyadmin to import the database and once imported it gives me this error:

Mistake
Static analysis:

6 errors were found during parsing.

A variable name was expected. (near "?" at position 1)
Unexpected start of statement. (near "?" at position 1)
Unexpected start of statement. (near "php" at position 2)
Unexpected start of statement. (near "defined" at position 6)
Unexpected start of statement. (near "'BASEPATH'" at position 14)
Unrecognized statement type. (near "OR" at position 26)
SQL Query: Copy

<?php defined('BASEPATH') OR exit('No direct script access allowed');

MySQL Message: Documentation

#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '<?php
defined('BASEPATH') OR exit('No direct script access allowed')' at line 1

Hope you can help me.
Davide

**Comment by kirilkirkov** [comment]
@Dodi-3009 
Can you give me more information:

- Where did you see these errors
- What are the steps which you do to start the application
- Provide some screenshots if you can

**Comment by juboy941** [comment]
There is a problem with the code affter setting up the database

**Comment by kirilkirkov** [comment]
@juboy941 
I have made a multiple tests and i can not catch the problem.
Import database.sql file to your database and then enter your mysql settings - database, username and password in application/config/database.php file.
Are you sure that you use MYSQL as database?
Attach screenshot of the error

**Comment by Dodi-3009** [comment]
I'm really sorry, I was wrong to do some processes and now I've succeeded, thanks a lot for your availability
