### ISSUE TITLE
Account

### ISSUE THREAD

**Issue by Dodi-3009** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#246]
hello, I'm trying to modify your project so that all users can log in and choose whether they are sellers or not in order to remember all their data at checkout, could you help me do this, because I'm not really very expert but I tried to do a part by modifying the seller's part, if you want the modified site it is this: http://bohdodiprova2.altervista.org/ for anything do not hesitate to write to me,
p.s. i modified your search/ lenguage toolbar and i think it's a bit cooler like that

**Comment by kirilkirkov** [comment]
Hello @Dodi-3009 
the easiest way is to enable the "Multi-Vendor Support" in /admin/settings and integrate a history of the payments of all logged users. To do this will need a code modifications which you are free to make.
