### ISSUE TITLE
Search bar and category

### ISSUE THREAD

**Issue by mossojn** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#249]
Great code. Real pleasure to check and work with it, but there are some issues: search bar doesn't not work, also can't see category after saving them (they are present but are not readable/visible).

**Comment by kirilkirkov** [comment]
Hello @mossojn 
Which theme you use? Currently i am making a test and the both features works

**Comment by mossojn** [comment]
Hello,
Thank you for your response. I use redlabel template currently. I'm also
trying to add a messenger system (buyer's can send messages to sellers to
get information about the products they sell) and a promotion system
(seller can activate it to promote their products).

**Comment by kirilkirkov** [comment]
@mossojn 
This commit should fix the issue - https://github.com/kirilkirkov/Ecommerce-CodeIgniter-Bootstrap/commit/d23c9ed530d48ff62e8a2ed030064b6f29594c7d
Currently should click the search icon to submit the form, i have made it to works with Enter button
