### ISSUE TITLE
A PHP Error was encountered 

### ISSUE THREAD

**Issue by huseyincakirca** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#252]
A PHP Error was encountered

Severity: Warning

Message: Undefined array key "iNFO"

Filename: core/Log.php

Line Number: 181

Backtrace:

File: /opt/lampp/htdocs/ecommerce/index.php
Line: 292
Function: require_once

gives this error even though the database is written correctly

**Comment by kirilkirkov** [comment]
@huseyincakirca 
In **index.php** file change
**define('ENVIRONMENT', 'development');**
to
**define('ENVIRONMENT', 'production');**

Its very strange that you see this error. have you made changes to the Codeigniter ?

**Comment by huseyincakirca** [comment]
thank you no problem
