### ISSUE TITLE
A PHP Error was encountered

### ISSUE THREAD

**Issue by fauwaz-911** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#254]
A PHP Error was encountered

Severity: 8192

Message: Creation of dynamic property CI_URI::$config is deprecated

Filename: core/URI.php

Line Number: 102

Backtrace:

File: /opt/lampp/htdocs/salescon1/index.php
Line: 292
Function: require_once
![image](https://github.com/kirilkirkov/Ecommerce-CodeIgniter-Bootstrap/assets/60237483/835e71a6-5b30-4934-9191-1e0a25d22480)

**Comment by kirilkirkov** [comment]
@fauwaz-911 
Which version of php you use?

**Comment by fauwaz-911** [comment]
I use php version 8.2.4

**Comment by kirilkirkov** [comment]
@fauwaz-911 
In php 8.2, dynamic properties are deprecated. You can use it with php 8.1 as latest.

If CodeIgniter Foundation make an update to version 3.1.13 , i will update this repo.

**Comment by fauwaz-911** [comment]
@kirilkirkov Okay, Thanks
