### ISSUE TITLE
A PHP Error was encountered

### ISSUE THREAD

**Issue by NirmaLKumar26** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#256]
A PHP Error was encountered
Severity: 8192

Message: Creation of dynamic property CI_URI::$config is deprecated
![image](https://github.com/kirilkirkov/Ecommerce-CodeIgniter-Bootstrap/assets/68182533/3ba07bab-b89c-4134-af1b-b0cb017aba40)

Please Let me know how to fix bro

**Comment by NirmaLKumar26** [comment]
You can see Demo : [Demo Link](https://tndev.in/e-commerce/v1/)

**Comment by kirilkirkov** [comment]
@NirmaLKumar26 Which version of php you use?

**Comment by NirmaLKumar26** [comment]
![image](https://github.com/kirilkirkov/Ecommerce-CodeIgniter-Bootstrap/assets/68182533/d3ab0a50-f10e-4da9-9067-e3f7b791ee8e)

**Comment by NirmaLKumar26** [comment]
its works, Thank you
