### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by lewismacnow** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#260]
**Host / App details:**

Ubuntu 20.04
PHP -v 7.4
MySQL 8.0.36-0ubuntu0.20.04.1

**What am I trying to do?**

I am trying to use your repo, I have:

0. cloned your repo into the root folder of a test website directory
1. Imported the sql file
2. updated the DB Config with appropriate username/pw

index.php opens fine albeit with some 404s for js libraries:

<img width="433" alt="image" src="https://github.com/kirilkirkov/Ecommerce-CodeIgniter-Bootstrap/assets/93997957/45c4f5d2-3635-4985-bced-f97d74c4a72b">

The index looks like this:

<img width="1274" alt="image" src="https://github.com/kirilkirkov/Ecommerce-CodeIgniter-Bootstrap/assets/93997957/7618ef6e-2c48-41a8-a414-a3c8aa4b2d2f">

Which looks pretty wrong anyway, but the biggest issue **none of the pages load/work**.

For example /admin and /shopping-cart fails to be found:

<img width="613" alt="image" src="https://github.com/kirilkirkov/Ecommerce-CodeIgniter-Bootstrap/assets/93997957/1c91b972-0827-4810-8b38-2b036d05307e">

Do you know what I am doing wrong?

**Comment by kirilkirkov** [comment]
Hello @lewismacnow 
did you enter your base_url into "/application/config/config.php" ?

**Comment by lewismacnow** [comment]
> Hello @lewismacnow did you enter your base_url into "/application/config/config.php" ?

Hi @kirilkirkov , I did (and have again now) seeing another issue where this was the proposed solution (#231).

This does not appear to help. I also do not see any errors in my webserver log.

![image](https://github.com/kirilkirkov/Ecommerce-CodeIgniter-Bootstrap/assets/93997957/55b1f245-09af-4733-8fdb-5a30320f8a48)

**Comment by kirilkirkov** [comment]
If you use NGINX as server, you should make it to use in same way like Apache with this .htaccess file:

`RewriteEngine on
 
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php?/$1 [L]`

**Comment by lewismacnow** [comment]
> If you use NGINX as server, you should make it to use in same way like Apache with this .htaccess file:
> 
> RewriteEngine on
> 
> RewriteCond %{REQUEST_FILENAME} !-f RewriteCond %{REQUEST_FILENAME} !-d RewriteRule ^(.*)$ index.php?/$1 [L]
> 
> Or if you use apache, make sure that .htaccess file is readable

Bingo! 

I am using Apache and my .htaccess was readable + contained a lot of content, adding these rows has made the webapp work correctly!

Thanks @kirilkirkov 

<img width="1204" alt="image" src="https://github.com/kirilkirkov/Ecommerce-CodeIgniter-Bootstrap/assets/93997957/91497fe8-f8f4-42d6-976e-29fd46676d90">
