### ISSUE TITLE
how to change currency

### ISSUE THREAD

**Issue by rambhai99** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#262]
how to change currency in this code

**Comment by kirilkirkov** [comment]
@rambhai99 
application/config/config.php 

There is a line:


/*
  |--------------------------------------------------------------------------
  | Default Language
  |--------------------------------------------------------------------------
  |
  | This determines which set of language files should be used. Make sure
  | there is an available translation if you intend to use something other
  | than english.
  | Must set currencyKey: BGN, USD or other.. Look in currency
  | hepler for help.. :)
  |
 */
$config['language'] = 'english';
$config['language_abbr'] = 'en';
$config['currency'] = '€';
$config['currencyKey'] = 'EUR';
