### ISSUE TITLE
No admin dir!

### ISSUE THREAD

**Issue by minne100** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#266]
After I setup everything, there is no admin dir!

**Comment by kirilkirkov** [comment]
Hi @minne100 
The administration is available at **/admin** url. Make sure that your .htaccess file works if you use Apache2 or check the configurations of nginx of the rewrite rules

**Comment by minne100** [comment]
Thank you. It's nginx setting problem.

________________________________
发件人: Kiril Kirkov ***@***.***>
发送时间: 2024年12月24日 15:23
收件人: kirilkirkov/Ecommerce-CodeIgniter-Bootstrap ***@***.***>
抄送: 汉语推广DAO ***@***.***>; Mention ***@***.***>
主题: Re: [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap] No admin dir! (Issue #266)


Hi @minne100<https://github.com/minne100>
The administration is available at /admin url. Make sure that your .htaccess file works if you use Apache2 or check the configurations of nginx of the rewrite rules

―
